import { useEffect, useMemo, useState } from "react";
import { apiJson } from "../../lib/api";
import { CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, FileText, Gift, Home, Paperclip, ReceiptText, Sparkles, Star, UserRound, WalletCards } from "lucide-react";
import { perks } from "../credit-ops/sample-data";
import "../../styles/client-credit.css";

type ClientAgenda = {
  cliente?: { id: string; nome: string; procedimento?: string | null };
  agendamentoAtivo?: { data?: string; horario?: string | null; previsaoLiberacaoFinanceira?: string | null } | null;
  agendamentoConcluido?: { data?: string; horario?: string | null; previsaoLiberacaoFinanceira?: string | null } | null;
  datasDisponiveis?: { id: string; data: string; vagasRestantes: number }[];
};
type ClientBoletos = { porcentagem_pagamento?: number; quantidade_parcelas?: number | null; boletos?: unknown[]; agenda_liberada?: boolean; status_revisao_financeira?: string | null };
type Tab = "inicio"|"contrato"|"pagamentos"|"agenda"|"clube";
type Journey = "eligible"|"analysis"|"payment"|"terms"|"signed"|"surgery_wait"|"surgery";

const fmt = (n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export function ClientCreditApp(){
  const [tab,setTab]=useState<Tab>("inicio");
  const [agenda,setAgenda]=useState<ClientAgenda|null>(null);
  const [boletos,setBoletos]=useState<ClientBoletos|null>(null);
  const [journey,setJourney]=useState<Journey>(()=>(localStorage.getItem("sra-client-journey") as Journey)||"eligible");
  const [proof,setProof]=useState<string[]>([]);
  const [points,setPoints]=useState(780);
  useEffect(()=>{Promise.all([apiJson<ClientAgenda>("/api/cliente/agenda",{cache:"no-store"}),apiJson<ClientBoletos>("/api/cliente/boletos",{cache:"no-store"})]).then(([a,b])=>{setAgenda(a);setBoletos(b)}).catch(()=>undefined)},[]);
  useEffect(()=>localStorage.setItem("sra-client-journey",journey),[journey]);
  const name=agenda?.cliente?.nome?.split(" ")[0]||"Renata";
  const percent=Math.max(68,boletos?.porcentagem_pagamento||0);
  const total=68000,paid=Math.round(total*percent/100),remaining=total-paid;
  const tabs=[['inicio','Início',Home],['contrato','Contrato',FileText],['pagamentos','Pagamentos',WalletCards],['agenda','Agenda',CalendarDays],['clube','Clube',Gift]] as const;
  return <div className="cl-app"><header><div><img src="/brand/sra-luck-mark.png"/><span>Olá, {name}</span></div><button><UserRound size={18}/></button></header><main>
    {tab==="inicio"&&<HomeTab name={name} percent={percent} paid={paid} total={total} remaining={remaining} journey={journey} setJourney={setJourney} setTab={setTab}/>} 
    {tab==="contrato"&&<ContractTab percent={percent} paid={paid} total={total} remaining={remaining}/>} 
    {tab==="pagamentos"&&<PaymentsTab proof={proof} setProof={setProof}/>} 
    {tab==="agenda"&&<AgendaTab journey={journey} setJourney={setJourney} available={agenda?.datasDisponiveis||[]}/>} 
    {tab==="clube"&&<ClubTab points={points} setPoints={setPoints}/>} 
  </main><nav>{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={18}/><span>{label}</span></button>)}</nav></div>
}

function HomeTab({name,percent,paid,total,remaining,journey,setJourney,setTab}:{name:string;percent:number;paid:number;total:number;remaining:number;journey:Journey;setJourney:(j:Journey)=>void;setTab:(t:Tab)=>void}){
 return <div className="cl-stack"><section className="cl-hero"><div><span>Seu progresso</span><h1>Olá, {name}. Seu sonho está avançando.</h1><p>Acompanhe seu contrato, pagamentos e cada etapa até a cirurgia.</p></div><ProgressRing percent={percent}/></section><section className="cl-card cl-contract"><div className="cl-card-head"><div><small>Meu contrato</small><strong>#10384 · Cirurgia programada</strong></div><span className="cl-chip green">Ativo</span></div><div className="cl-values"><div><small>Valor do contrato</small><b>{fmt(total)}</b></div><div><small>Valor pago</small><b>{fmt(paid)}</b></div><div><small>Saldo restante</small><b>{fmt(remaining)}</b></div></div><div className="cl-threshold"><Star size={18}/><div><strong>A partir de 60% você inicia o processo cirúrgico</strong><span>Você já atingiu {percent}% do valor do contrato.</span></div></div></section><JourneyCard journey={journey} setJourney={setJourney} setTab={setTab}/><section className="cl-card cl-quick"><button onClick={()=>setTab("pagamentos")}><ReceiptText/><span>Minhas parcelas<small>Boletos, comprovantes e cartão</small></span><ChevronRight/></button><button onClick={()=>setTab("clube")}><Gift/><span>Clube de Vantagens<small>780 pontos disponíveis</small></span><ChevronRight/></button></section></div>
}
function ProgressRing({percent}:{percent:number}){return <div className="cl-ring" style={{background:`conic-gradient(#a9844f ${percent*3.6}deg,#eadfce 0)`}}><div><b>{percent}%</b><span>valor pago</span></div></div>}
function JourneyCard({journey,setJourney,setTab}:{journey:Journey;setJourney:(j:Journey)=>void;setTab:(t:Tab)=>void}){
 const data:Record<Journey,{title:string;text:string,action:string,next?:Journey}>={eligible:{title:"Você já pode solicitar seus termos cirúrgicos",text:"Ao solicitar, nosso financeiro fará o levantamento do saldo e das formas de pagamento. Prazo de até 5 dias úteis.",action:"Solicitar agendamento dos termos",next:"analysis"},analysis:{title:"Levantamento financeiro em andamento",text:"Recebemos sua solicitação. Nossa equipe está conferindo o saldo e as opções disponíveis para o seu contrato.",action:"Acompanhar solicitação"},payment:{title:"Escolha como quitar o valor restante",text:"Seu levantamento foi aprovado. Selecione a forma disponível e escolha pagar agora ou no dia da assinatura.",action:"Escolher forma de pagamento",next:"terms"},terms:{title:"Agenda dos termos liberada",text:"Escolha uma data e horário disponibilizados pela nossa equipe para assinatura dos termos cirúrgicos.",action:"Escolher data e horário"},signed:{title:"Termos assinados",text:"Agora precisamos confirmar a quitação do saldo restante para seguir para a liberação cirúrgica.",action:"Ver saldo final",next:"surgery_wait"},surgery_wait:{title:"Preparando sua agenda cirúrgica",text:"Com saldo quitado e termos assinados, a agenda da cirurgia será liberada em até 5 dias úteis.",action:"Acompanhar liberação"},surgery:{title:"Agenda cirúrgica liberada!",text:"Agora você já pode escolher sua data de cirurgia entre os períodos disponibilizados.",action:"Escolher data da cirurgia"}};
 const d=data[journey];return <section className="cl-card cl-journey"><div className="cl-icon"><Sparkles/></div><div><small>Próxima etapa</small><h2>{d.title}</h2><p>{d.text}</p></div><button onClick={()=>{if(journey==="terms"||journey==="surgery")setTab("agenda");else if(d.next)setJourney(d.next)}}>{d.action}<ChevronRight size={16}/></button>{journey==="analysis"&&<div className="cl-demo"><button onClick={()=>setJourney("payment")}>Simular levantamento aprovado</button></div>}{journey==="surgery_wait"&&<div className="cl-demo"><button onClick={()=>setJourney("surgery")}>Simular 5 dias úteis concluídos</button></div>}</section>
}
function ContractTab({percent,paid,total,remaining}:{percent:number;paid:number;total:number;remaining:number}){const steps=["Contrato confirmado","Parcelas geradas","Em formação de saldo","Percentual mínimo atingido","Levantamento financeiro","Termos cirúrgicos","Quitação final","Agenda cirúrgica","Cirurgia realizada"];return <div className="cl-stack"><div className="cl-section-title"><h1>Meu contrato</h1><p>Visão completa do seu progresso.</p></div><section className="cl-card"><div className="cl-contract-top"><ProgressRing percent={percent}/><div><small>Contrato #10384</small><h2>Carta de crédito · Cirurgia programada</h2><span className="cl-chip green">Em andamento</span></div></div><div className="cl-values"><div><small>Total</small><b>{fmt(total)}</b></div><div><small>Pago</small><b>{fmt(paid)}</b></div><div><small>Restante</small><b>{fmt(remaining)}</b></div></div></section><section className="cl-card"><h2>Etapas do processo</h2><ol className="cl-timeline">{steps.map((s,i)=><li className={i<4?"done":i===4?"active":""} key={s}><span>{i<4?<CheckCircle2 size={15}/>:i+1}</span><div><strong>{s}</strong><small>{i<4?"Concluído":i===4?"Próxima etapa":"Aguardando etapas anteriores"}</small></div></li>)}</ol></section></div>}
function PaymentsTab({proof,setProof}:{proof:string[];setProof:(v:string[])=>void}){const parcels=Array.from({length:6},(_,i)=>({n:i+1,due:`10/${String(10+i).padStart(2,'0')}/2026`,value:1133.33,status:i<3?'Pago':i===3?'Em análise':'A vencer'}));return <div className="cl-stack"><div className="cl-section-title"><h1>Pagamentos</h1><p>Boletos, cartão e comprovantes em um só lugar.</p></div><section className="cl-card"><div className="cl-payment-summary"><div><small>Próxima parcela</small><b>{fmt(1133.33)}</b><span>10/01/2027</span></div><button><CreditCard size={17}/>Pagar com cartão</button></div></section>{parcels.map(p=><section className="cl-card cl-parcel" key={p.n}><div><span className={`cl-chip ${p.status==='Pago'?'green':p.status==='Em análise'?'amber':''}`}>{p.status}</span><strong>Parcela {p.n}/60</strong><small>Vencimento {p.due}</small></div><b>{fmt(p.value)}</b><div className="cl-parcel-actions"><button>Ver boleto</button><label><Paperclip size={15}/>Anexar comprovante<input type="file" onChange={e=>{if(e.target.files?.[0])setProof([...proof,e.target.files[0].name])}}/></label></div></section>)}{proof.length>0&&<section className="cl-card"><h2>Comprovantes enviados</h2>{proof.map(x=><div className="cl-proof" key={x}><CheckCircle2 size={17}/><span>{x}</span><b>Em análise</b></div>)}</section>}</div>}
function AgendaTab({journey,setJourney,available}:{journey:Journey;setJourney:(j:Journey)=>void;available:{id:string;data:string;vagasRestantes:number}[]}){const [selected,setSelected]=useState<string|null>(null);const dates=available.length?available.slice(0,6):[{id:'1',data:'2026-09-22',vagasRestantes:3},{id:'2',data:'2026-09-24',vagasRestantes:2},{id:'3',data:'2026-09-29',vagasRestantes:4}];const surgery=journey==='surgery';return <div className="cl-stack"><div className="cl-section-title"><h1>{surgery?'Agenda cirúrgica':'Agenda dos termos'}</h1><p>{surgery?'Escolha a data disponível para sua cirurgia.':'Escolha a data e horário para assinatura dos termos.'}</p></div><section className="cl-card"><div className="cl-agenda-info"><CalendarDays/><div><strong>{surgery?'Sua agenda cirúrgica está liberada':'Horários liberados pela Sra. Luck'}</strong><small>{surgery?'A liberação acontece após termos assinados e saldo quitado.':'Você pode reagendar se não conseguir quitar o saldo na data dos termos.'}</small></div></div></section><div className="cl-date-grid">{dates.map(d=><button className={selected===d.id?'selected':''} key={d.id} onClick={()=>setSelected(d.id)}><span>{new Date(`${d.data}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short'})}</span><b>{new Date(`${d.data}T12:00:00`).getDate()}</b><small>{d.vagasRestantes} horários</small></button>)}</div>{selected&&<section className="cl-card"><h2>Horários disponíveis</h2><div className="cl-time-grid">{['08:00','09:00','10:00','11:00','13:00','14:00','15:00','16:00'].map(t=><button key={t}>{t}</button>)}</div><button className="cl-primary" onClick={()=>setJourney(surgery?'surgery':'signed')}>Confirmar agendamento</button></section>}</div>}
function ClubTab({points,setPoints}:{points:number;setPoints:(n:number)=>void}){const [redeemed,setRedeemed]=useState<string[]>([]);return <div className="cl-stack"><section className="cl-club-hero"><Gift/><div><span>Clube de Vantagens</span><h1>{points} pontos</h1><p>Indique amigas e transforme suas indicações em mimos e experiências.</p></div></section><section className="cl-card cl-referral"><div><strong>Indique e ganhe pontos</strong><p>Compartilhe seu código. Após a indicação ser validada, seus pontos entram automaticamente.</p></div><button>Compartilhar meu código</button></section><div className="cl-section-title"><h2>Troque seus pontos</h2><p>Benefícios podem ser atualizados pela Sra. Luck.</p></div><div className="cl-perks">{perks.map(p=><article key={p.id}><div className="cl-perk-art"><Sparkles/></div><span>{p.category}</span><h3>{p.title}</h3><p>{p.description}</p><strong>{p.points} pontos</strong><button disabled={points<p.points||redeemed.includes(p.id)} onClick={()=>{setPoints(points-p.points);setRedeemed([...redeemed,p.id])}}>{redeemed.includes(p.id)?'Resgatado':points>=p.points?'Resgatar':'Pontos insuficientes'}</button></article>)}</div></div>}
