import { useEffect, useState } from "react";
import { CalendarDays, CheckCircle2, ChevronRight, CreditCard, FileText, Gift, Home, LoaderCircle, Paperclip, ReceiptText, RefreshCw, Sparkles, Star, WalletCards } from "lucide-react";
import { requestJson } from "../../lib/http";
import "../../styles/client-credit.css";

type Stage = "nova_venda"|"aguardando_conferencia"|"formacao_saldo"|"proxima_meta"|"meta_atingida"|"levantamento_financeiro"|"forma_pagamento_liberada"|"termos_agendados"|"aguardando_quitacao"|"quitado"|"agenda_cirurgica_liberada"|"cirurgia_agendada"|"concluido"|"cancelado";
type Contract = { id:string; codigo:string; valor_contrato:number|string; percentual_minimo:number|string; etapa:Stage; modalidade:"flex"|"100_boleto"; saldo_final_apurado?:number|string|null; formas_quitacao_disponiveis?:string[]; forma_quitacao?:string|null; pagar_no_dia_termos?:boolean; levantamento_prazo_ate?:string|null; termos_assinados_em?:string|null; agenda_cirurgica_liberar_em?:string|null; cirurgia_em?:string|null };
type Installment = { id:string; numero_parcela:number; total_parcelas?:number|null; valor:number|string; status:string; data_vencimento:string; data_pagamento?:string|null; valor_recebido?:number|string|null; comprovante_url?:string|null; boleto_url?:string|null; banco_emissor?:string|null };
type Journey = { contrato:Contract|null; parcelas:Installment[]; paid:number; total:number; percent:number; remaining:number };
type WindowItem = { id:string; tipo:"termos"|"cirurgia"; data:string; horario_inicio:string; horario_fim?:string|null; vagas:number; vagasRestantes:number };
type Club = { saldo:number; recompensas:{id:string;titulo:string;descricao?:string;categoria?:string;pontos:number;estoque?:number|null;imagem_url?:string|null}[]; historico:unknown[] };
type Tab="inicio"|"contrato"|"pagamentos"|"agenda"|"clube";
type ClientAgendaSummary = { cliente?: { nome?: string | null } | null };
type AgendaKind = "termos"|"cirurgia";

const money=(value:number|string|undefined|null)=>Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const date=(value?:string|null)=>value?new Date(`${value.length===10?value+"T12:00:00":value}`).toLocaleDateString("pt-BR"):"—";
const api = requestJson;

export function ClientCreditLiveApp(){
 const [tab,setTab]=useState<Tab>("inicio");
 const [journey,setJourney]=useState<Journey|null>(null);
 const [name,setName]=useState("Cliente");
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState<string|null>(null);
 async function reload(){setLoading(true);setError(null);try{const [j,a]=await Promise.all([api<Journey>("/api/cliente/journey",{cache:"no-store"}),api<ClientAgendaSummary>("/api/cliente/agenda",{cache:"no-store"}).catch(()=>null)]);setJourney(j);if(a?.cliente?.nome)setName(String(a.cliente.nome).split(" ")[0])}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar seus dados.")}finally{setLoading(false)}}
 useEffect(()=>{void reload()},[]);
 const tabs=[['inicio','Início',Home],['contrato','Contrato',FileText],['pagamentos','Pagamentos',WalletCards],['agenda','Agenda',CalendarDays],['clube','Clube',Gift]] as const;
 if(loading&&!journey)return <Loading/>;
 if(error&&!journey)return <ErrorState message={error} retry={reload}/>;
 if(!journey?.contrato)return <ErrorState message="Ainda não encontramos um contrato ativo para este acesso." retry={reload}/>;
 return <div className="cl-app"><header><div><img src="/brand/sra-luck-mark.png" alt="Sra. Luck"/><span>Olá, {name}</span></div><button onClick={()=>void reload()} aria-label="Atualizar"><RefreshCw size={17}/></button></header><main>
 {error&&<div className="cl-inline-error">{error}</div>}
 {tab==='inicio'&&<LiveHome name={name} data={journey} reload={reload} setTab={setTab}/>} 
 {tab==='contrato'&&<LiveContract data={journey}/>} 
 {tab==='pagamentos'&&<LivePayments data={journey} reload={reload}/>} 
 {tab==='agenda'&&<LiveAgenda data={journey} reload={reload}/>} 
 {tab==='clube'&&<LiveClub/>}
 </main><nav>{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/><span>{label}</span></button>)}</nav></div>
}

function Loading(){return <main className="cl-loading"><img src="/brand/sra-luck-mark.png" alt="Sra. Luck"/><LoaderCircle className="spin"/><strong>Carregando seu progresso...</strong></main>}
function ErrorState({message,retry}:{message:string;retry:()=>Promise<void>}){return <main className="cl-loading"><img src="/brand/sra-luck-mark.png" alt="Sra. Luck"/><strong>{message}</strong><button onClick={()=>void retry()}>Tentar novamente</button></main>}
function ProgressRing({percent}:{percent:number}){const p=Math.max(0,Math.min(100,percent));return <div className="cl-ring" style={{background:`conic-gradient(#a9844f ${p*3.6}deg,#eadfce 0)`}}><div><b>{Math.round(p)}%</b><span>valor pago</span></div></div>}

function LiveHome({name,data,reload,setTab}:{name:string;data:Journey;reload:()=>Promise<void>;setTab:(t:Tab)=>void}){
 const c=data.contrato!; const eligible=data.percent>=Number(c.percentual_minimo); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
 async function requestTerms(){setBusy(true);setMessage(null);try{const result=await api<{prazoAte?:string}>("/api/cliente/journey/request-terms",{method:"POST",body:"{}"},{retryUnsafe:true});setMessage(result.prazoAte?`Solicitação recebida. Prazo estimado: ${date(result.prazoAte)}.`:"Solicitação recebida.");await reload()}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível enviar a solicitação.")}finally{setBusy(false)}}
 return <div className="cl-stack"><section className="cl-hero"><div><span>Seu progresso</span><h1>Olá, {name}. Seu planejamento está avançando.</h1><p>Acompanhe pagamentos, termos e cada etapa até a sua cirurgia.</p></div><ProgressRing percent={data.percent}/></section><section className="cl-card cl-contract"><div className="cl-card-head"><div><small>Meu contrato</small><strong>{c.codigo} · {c.modalidade==='flex'?'Contrato Flex':'100% boleto'}</strong></div><span className="cl-chip green">Ativo</span></div><div className="cl-values"><div><small>Valor do contrato</small><b>{money(data.total)}</b></div><div><small>Valor pago</small><b>{money(data.paid)}</b></div><div><small>Saldo restante</small><b>{money(data.remaining)}</b></div></div><div className="cl-threshold"><Star size={18}/><div><strong>A partir de {Number(c.percentual_minimo)}% você pode iniciar o processo dos termos</strong><span>{eligible?`Meta atingida: ${Math.round(data.percent)}% pagos.`:`Faltam ${money(Math.max(0,data.total*Number(c.percentual_minimo)/100-data.paid))} para atingir a meta.`}</span></div></div></section><LiveJourneyAction data={data} busy={busy} requestTerms={requestTerms} reload={reload} setTab={setTab}/>{message&&<div className="cl-notice">{message}</div>}<section className="cl-card cl-quick"><button onClick={()=>setTab('pagamentos')}><ReceiptText/><span>Minhas parcelas<small>Boletos, comprovantes e cartão</small></span><ChevronRight/></button><button onClick={()=>setTab('clube')}><Gift/><span>Clube de Vantagens<small>Indique, pontue e resgate</small></span><ChevronRight/></button></section></div>
}

function LiveJourneyAction({data,busy,requestTerms,reload,setTab}:{data:Journey;busy:boolean;requestTerms:()=>Promise<void>;reload:()=>Promise<void>;setTab:(t:Tab)=>void}){
 const c=data.contrato!; const [showPayment,setShowPayment]=useState(false);
 const content:Record<Stage,{title:string;text:string,action?:string}>={
  nova_venda:{title:"Seu contrato foi recebido",text:"Nossa equipe fará a conferência dos dados e da geração das parcelas."},aguardando_conferencia:{title:"Contrato em conferência",text:"Estamos validando os dados do contrato e os boletos antes de liberar o acompanhamento completo."},formacao_saldo:{title:"Continue formando seu saldo",text:`Quando você atingir ${Number(c.percentual_minimo)}%, o botão para solicitar seus termos será liberado.`},proxima_meta:{title:"Você está perto da próxima etapa",text:`Falta pouco para atingir ${Number(c.percentual_minimo)}% e iniciar o processo cirúrgico.`},meta_atingida:{title:"Você já pode solicitar seus termos cirúrgicos",text:"Depois da solicitação, realizaremos o levantamento financeiro em até 5 dias úteis.",action:"Solicitar agendamento dos termos"},levantamento_financeiro:{title:"Levantamento financeiro em andamento",text:`Nossa equipe está apurando seu saldo e as opções de pagamento. Prazo previsto: ${date(c.levantamento_prazo_ate)}.`},forma_pagamento_liberada:{title:"Escolha a forma de pagamento do valor restante",text:`Saldo apurado: ${money(c.saldo_final_apurado)}. Depois da escolha, sua agenda de termos será disponibilizada.`,action:"Escolher forma de pagamento"},termos_agendados:{title:"Assinatura dos termos agendada",text:"No dia da assinatura, o saldo restante deve estar quitado. Se precisar, você poderá reagendar.",action:"Ver minha agenda"},aguardando_quitacao:{title:"Aguardando quitação final",text:`Termos assinados. Saldo final: ${money(c.saldo_final_apurado)}. A agenda cirúrgica só é liberada após a quitação.`},quitado:{title:"Saldo quitado com sucesso",text:`Sua agenda cirúrgica será liberada em até 5 dias úteis após a assinatura. Previsão: ${date(c.agenda_cirurgica_liberar_em)}.`},agenda_cirurgica_liberada:{title:"Agenda cirúrgica liberada!",text:"Agora você já pode escolher a data disponível para sua cirurgia.",action:"Escolher data da cirurgia"},cirurgia_agendada:{title:"Sua cirurgia está agendada",text:`Data prevista: ${date(c.cirurgia_em)}. Continue acompanhando as orientações no aplicativo.`},concluido:{title:"Jornada concluída",text:"Seu processo foi concluído. Obrigada por confiar na Sra. Luck."},cancelado:{title:"Contrato encerrado",text:"Entre em contato com a equipe para mais informações."}
 };
 const d=content[c.etapa];
 return <section className="cl-card cl-journey"><div className="cl-icon"><Sparkles/></div><div><small>Etapa atual</small><h2>{d.title}</h2><p>{d.text}</p></div>{d.action&&<button disabled={busy} onClick={()=>{if(c.etapa==='meta_atingida')void requestTerms();else if(c.etapa==='forma_pagamento_liberada')setShowPayment(true);else setTab('agenda')}}>{busy?'Enviando...':d.action}<ChevronRight size={16}/></button>}{showPayment&&<PaymentChoice contract={c} onClose={()=>setShowPayment(false)} onSaved={async()=>{setShowPayment(false);await reload();setTab('agenda')}}/>}</section>
}

function PaymentChoice({contract,onClose,onSaved}:{contract:Contract;onClose:()=>void;onSaved:()=>Promise<void>}){
 const forms=contract.formas_quitacao_disponiveis||[]; const [form,setForm]=useState(forms[0]||""); const [when,setWhen]=useState<"agora"|"dia_termos">("agora"); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 async function save(){setBusy(true);setError(null);try{await api("/api/cliente/journey/payment-choice",{method:"POST",body:JSON.stringify({forma:form,quando:when})},{retryUnsafe:true});await onSaved()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar sua escolha.")}finally{setBusy(false)}}
 return <div className="cl-modal-backdrop"><div className="cl-modal"><h2>Pagamento do valor restante</h2><p>Saldo apurado: <strong>{money(contract.saldo_final_apurado)}</strong></p><h3>Forma de pagamento</h3>{forms.map(x=><label className="cl-choice" key={x}><input type="radio" name="forma" checked={form===x} onChange={()=>setForm(x)}/><span>{labelPayment(x)}</span></label>)}<h3>Quando deseja pagar?</h3><label className="cl-choice"><input type="radio" name="quando" checked={when==='agora'} onChange={()=>setWhen('agora')}/><span>Pagar agora</span></label><label className="cl-choice"><input type="radio" name="quando" checked={when==='dia_termos'} onChange={()=>setWhen('dia_termos')}/><span>Pagar no dia da assinatura dos termos</span></label>{error&&<div className="cl-inline-error">{error}</div>}<div className="cl-modal-actions"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!form||busy} onClick={()=>void save()}>{busy?'Salvando...':'Confirmar escolha'}</button></div></div></div>
}
const labelPayment=(x:string)=>({pix:"PIX",cartao:"Cartão de crédito",cheque:"Cheque",boleto:"Boleto"}[x]||x);

function LiveContract({data}:{data:Journey}){const c=data.contrato!;const all=["Venda recebida","Conferência do contrato","Parcelas geradas","Em formação de saldo","Percentual mínimo atingido","Levantamento financeiro","Forma de pagamento liberada","Termos agendados","Quitação final","Agenda cirúrgica liberada","Cirurgia agendada"];const index:Record<Stage,number>={nova_venda:0,aguardando_conferencia:1,formacao_saldo:3,proxima_meta:3,meta_atingida:4,levantamento_financeiro:5,forma_pagamento_liberada:6,termos_agendados:7,aguardando_quitacao:8,quitado:8,agenda_cirurgica_liberada:9,cirurgia_agendada:10,concluido:10,cancelado:0};const current=index[c.etapa];return <div className="cl-stack"><div className="cl-section-title"><h1>Meu contrato</h1><p>Visão completa do seu progresso e das próximas etapas.</p></div><section className="cl-card"><div className="cl-contract-top"><ProgressRing percent={data.percent}/><div><small>{c.codigo}</small><h2>{c.modalidade==='flex'?'Contrato Flex':'Contrato 100% boleto'}</h2><span className="cl-chip green">{Math.round(data.percent)}% pago</span></div></div><div className="cl-values"><div><small>Total</small><b>{money(data.total)}</b></div><div><small>Pago</small><b>{money(data.paid)}</b></div><div><small>Restante</small><b>{money(data.remaining)}</b></div></div></section><section className="cl-card"><h2>Etapas do processo</h2><ol className="cl-timeline">{all.map((s,i)=><li className={i<current?'done':i===current?'active':''} key={s}><span>{i<current?<CheckCircle2 size={15}/>:i+1}</span><div><strong>{s}</strong><small>{i<current?'Concluído':i===current?'Etapa atual':'Aguardando etapas anteriores'}</small></div></li>)}</ol></section></div>}

function LivePayments({data,reload}:{data:Journey;reload:()=>Promise<void>}){const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);async function upload(id:string,file:File){if(file.size>5*1024*1024){setMessage("O arquivo deve ter no máximo 5 MB.");return}setBusy(id);try{const fd=new FormData();fd.append("arquivo",file);await api(`/api/cliente/boletos/${encodeURIComponent(id)}/anexar`,{method:"POST",body:fd},{timeoutMs:20_000});setMessage("Comprovante enviado. A parcela entrou em análise.");await reload()}catch(e){setMessage(e instanceof Error?e.message:"Falha no envio.")}finally{setBusy(null)}}async function card(id:string){setBusy(id);try{const result=await api<{checkoutUrl:string}>("/api/cliente/payments/mercado-pago/preference",{method:"POST",body:JSON.stringify({boletoId:id})},{retryUnsafe:true});if(!result.checkoutUrl)throw new Error("O checkout não foi disponibilizado.");window.location.href=result.checkoutUrl}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível abrir o pagamento.")}finally{setBusy(null)}}return <div className="cl-stack"><div className="cl-section-title"><h1>Pagamentos</h1><p>Boletos, cartão e comprovantes vinculados à parcela correta.</p></div>{message&&<div className="cl-notice">{message}</div>}{data.parcelas.map(p=><section className="cl-card cl-parcel" key={p.id}><div><span className={`cl-chip ${p.status==='pago'?'green':p.comprovante_url?'amber':''}`}>{p.status==='pago'?'Pago':p.comprovante_url?'Em análise':new Date(`${p.data_vencimento}T23:59:59`)<new Date()?'Vencida':'A vencer'}</span><strong>Parcela {p.numero_parcela}/{p.total_parcelas||data.parcelas.length}</strong><small>Vencimento {date(p.data_vencimento)}{p.banco_emissor?` · ${p.banco_emissor}`:''}</small></div><b>{money(p.valor)}</b><div className="cl-parcel-actions">{p.boleto_url?<a href={`/api/cliente/boletos/${encodeURIComponent(p.id)}/arquivo`} target="_blank" rel="noreferrer">Ver boleto</a>:<button disabled>Boleto indisponível</button>}<button disabled={p.status==='pago'||busy===p.id} onClick={()=>void card(p.id)}><CreditCard size={14}/>Pagar com cartão</button><label><Paperclip size={15}/>{busy===p.id?'Enviando...':'Anexar comprovante'}<input type="file" accept="image/jpeg,image/png,application/pdf" disabled={busy===p.id||p.status==='pago'} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(p.id,file)}}/></label></div></section>)}</div>}

function LiveAgenda({data,reload}:{data:Journey;reload:()=>Promise<void>}){const c=data.contrato!;const type:AgendaKind = c.etapa==='agenda_cirurgica_liberada'||c.etapa==='cirurgia_agendada'?'cirurgia':'termos';const [windows,setWindows]=useState<WindowItem[]>([]);const [selected,setSelected]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState<string|null>(null);useEffect(()=>{setLoading(true);api<{janelas:WindowItem[];bloqueado?:boolean;liberarEm?:string}>(`/api/cliente/journey/windows?tipo=${type}`,{cache:"no-store"}).then(r=>{setWindows(r.janelas||[]);if(r.bloqueado)setMessage(r.liberarEm?`Agenda será liberada a partir de ${date(r.liberarEm)}.`:"Esta agenda ainda não está liberada para seu contrato.")}).catch(e=>setMessage(e instanceof Error?e.message:"Falha ao carregar agenda.")).finally(()=>setLoading(false))},[type,c.etapa]);async function schedule(){if(!selected)return;setLoading(true);try{await api("/api/cliente/journey/schedule",{method:"POST",body:JSON.stringify({tipo:type,janelaId:selected})},{retryUnsafe:true});setMessage(type==='termos'?"Assinatura dos termos agendada com sucesso.":"Cirurgia agendada com sucesso.");await reload()}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível agendar.")}finally{setLoading(false)}}return <div className="cl-stack"><div className="cl-section-title"><h1>{type==='cirurgia'?'Agenda cirúrgica':'Agenda dos termos'}</h1><p>{type==='cirurgia'?'Escolha a data disponibilizada para sua cirurgia.':'As datas abaixo foram liberadas pela equipe Sra. Luck.'}</p></div><section className="cl-card"><div className="cl-agenda-info"><CalendarDays/><div><strong>{type==='cirurgia'?'Liberação cirúrgica':'Assinatura dos termos'}</strong><small>{type==='cirurgia'?`Termos e quitação confirmados. Liberação prevista: ${date(c.agenda_cirurgica_liberar_em)}.`:'Se não conseguir quitar o saldo até a assinatura, você poderá reagendar.'}</small></div></div></section>{message&&<div className="cl-notice">{message}</div>}{loading?<section className="cl-card">Carregando horários...</section>:windows.length===0?<section className="cl-card"><p className="cl-empty">Nenhum horário disponível neste momento. Novas datas serão publicadas pela equipe.</p></section>:<><div className="cl-window-list">{windows.map(w=><button key={w.id} className={selected===w.id?'selected':''} onClick={()=>setSelected(w.id)}><CalendarDays/><div><strong>{date(w.data)}</strong><small>{w.horario_inicio.slice(0,5)}{w.horario_fim?` – ${w.horario_fim.slice(0,5)}`:''}</small></div><span>{w.vagasRestantes} vaga(s)</span></button>)}</div>{selected&&<button className="cl-primary" onClick={()=>void schedule()}>{loading?'Confirmando...':'Confirmar agendamento'}</button>}</>}</div>}

function LiveClub(){const [club,setClub]=useState<Club|null>(null);const [error,setError]=useState<string|null>(null);const [referral,setReferral]=useState(false);async function load(){try{setClub(await api<Club>("/api/cliente/credit-ops/club",{cache:"no-store"}))}catch(e){setError(e instanceof Error?e.message:"Não foi possível abrir o clube.")}}useEffect(()=>{void load()},[]);async function redeem(id:string){try{await api("/api/cliente/credit-ops/redeem",{method:"POST",body:JSON.stringify({recompensaId:id})},{retryUnsafe:true});await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível resgatar.")}}if(!club)return <div className="cl-stack"><div className="cl-section-title"><h1>Clube de Vantagens</h1></div><section className="cl-card">{error||"Carregando seus pontos..."}</section></div>;return <div className="cl-stack"><section className="cl-club-hero"><Gift/><div><span>Clube de Vantagens</span><h1>{club.saldo} pontos</h1><p>Indique pessoas e transforme suas indicações validadas em mimos e experiências.</p></div></section><section className="cl-card cl-referral"><div><strong>Indique e ganhe pontos</strong><p>Cadastre uma indicação para nossa equipe acompanhar.</p></div><button onClick={()=>setReferral(true)}>Fazer indicação</button></section>{error&&<div className="cl-inline-error">{error}</div>}<div className="cl-section-title"><h2>Troque seus pontos</h2><p>Benefícios ativos no Clube Sra. Luck.</p></div><div className="cl-perks">{club.recompensas.map(p=><article key={p.id}><div className="cl-perk-art"><Sparkles/></div><span>{p.categoria||"Benefício"}</span><h3>{p.titulo}</h3><p>{p.descricao||"Benefício exclusivo Sra. Luck."}</p><strong>{p.pontos} pontos</strong><button disabled={club.saldo<p.pontos} onClick={()=>void redeem(p.id)}>{club.saldo>=p.pontos?'Resgatar':'Pontos insuficientes'}</button></article>)}</div>{referral&&<ReferralModal onClose={()=>setReferral(false)} onSaved={()=>setReferral(false)}/>}</div>}
function ReferralModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [name,setName]=useState("");const [phone,setPhone]=useState("");const [error,setError]=useState<string|null>(null);async function save(){try{await api("/api/cliente/credit-ops/referrals",{method:"POST",body:JSON.stringify({nome:name.trim(),telefone:phone.trim()})},{retryUnsafe:true});onSaved()}catch(e){setError(e instanceof Error?e.message:"Falha ao enviar indicação.")}}return <div className="cl-modal-backdrop"><div className="cl-modal"><h2>Indicar uma pessoa</h2><p>Os pontos serão creditados após a indicação cumprir os critérios definidos pela Sra. Luck.</p><label>Nome<input maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Telefone<input maxLength={30} inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label>{error&&<div className="cl-inline-error">{error}</div>}<div className="cl-modal-actions"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!name.trim()} onClick={()=>void save()}>Enviar indicação</button></div></div></div>}
