-- SRA. LUCK — MIGRATIONS FINAIS DE PRODUÇÃO
-- Data: 2026-09-11
-- Pré-requisito: migrations legadas até migration_022_operacao_credito_ecossistema.sql executadas.
-- Este arquivo é idempotente: pode ser executado novamente sem duplicar estruturas ou seeds.

begin;

create extension if not exists pgcrypto;

create table if not exists public.schema_migrations (
  version text primary key,
  description text not null,
  applied_at timestamptz not null default now()
);
comment on table public.schema_migrations is 'Controle das migrations finais do ecossistema Sra. Luck. Usada pela equipe técnica para auditoria de schema.';
revoke all on public.schema_migrations from anon, authenticated;

-- =============================================================================
-- 001_20260911_observabilidade_auditoria
-- O que: trilha de auditoria imutável e métricas de requisição.
-- Por quê: rastrear acessos, alterações críticas, latência e taxa de erro.
-- Quem usa: Cloudflare Worker e diretoria/gestão por relatórios internos.
-- =============================================================================
create table if not exists public.audit_log (
  id uuid primary key default gen_random_uuid(),
  actor_type text not null check (actor_type in ('admin','cliente','equipe','sistema','database')),
  actor_id text,
  action text not null check (char_length(action) between 1 and 120),
  entity_type text not null check (char_length(entity_type) between 1 and 120),
  entity_id text,
  request_id text,
  ip_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
comment on table public.audit_log is 'Registro imutável de ações importantes: quem fez, quando, qual ação e qual entidade. Gravado pelo Worker e por triggers de banco.';
create index if not exists audit_log_actor_idx on public.audit_log(actor_type, actor_id, created_at desc);
create index if not exists audit_log_entity_idx on public.audit_log(entity_type, entity_id, created_at desc);
create index if not exists audit_log_created_idx on public.audit_log(created_at desc);

create table if not exists public.api_request_metrics (
  id bigint generated by default as identity primary key,
  request_id text,
  route text not null,
  method text not null,
  status_code integer not null check (status_code between 100 and 599),
  duration_ms integer not null check (duration_ms >= 0),
  actor_type text,
  actor_id text,
  created_at timestamptz not null default now()
);
comment on table public.api_request_metrics is 'Métricas operacionais de APIs para requests/min, taxa de erro e latência. Escrita pelo Worker; leitura restrita à gestão técnica.';
create index if not exists api_request_metrics_created_idx on public.api_request_metrics(created_at desc);
create index if not exists api_request_metrics_status_idx on public.api_request_metrics(status_code, created_at desc);
create index if not exists api_request_metrics_route_idx on public.api_request_metrics(route, created_at desc);

create or replace function public.audit_critical_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_log(actor_type, actor_id, action, entity_type, entity_id, metadata)
  values (
    'database',
    null,
    lower(tg_op),
    tg_table_name,
    coalesce((to_jsonb(new)->>'id'), (to_jsonb(old)->>'id')),
    jsonb_build_object(
      'changed_at', now(),
      'old', case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) - array['cpf','email','telefone','data_nascimento'] else null end,
      'new', case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) - array['cpf','email','telefone','data_nascimento'] else null end
    )
  );
  return coalesce(new, old);
end;
$$;
revoke all on function public.audit_critical_change() from public;
grant execute on function public.audit_critical_change() to service_role;

do $$
begin
  if to_regclass('public.clientes') is not null then
    drop trigger if exists audit_clientes_change on public.clientes;
    create trigger audit_clientes_change after insert or update or delete on public.clientes for each row execute function public.audit_critical_change();
  end if;
  if to_regclass('public.contratos_credito') is not null then
    drop trigger if exists audit_contratos_credito_change on public.contratos_credito;
    create trigger audit_contratos_credito_change after insert or update or delete on public.contratos_credito for each row execute function public.audit_critical_change();
  end if;
  if to_regclass('public.boletos') is not null then
    drop trigger if exists audit_boletos_change on public.boletos;
    create trigger audit_boletos_change after insert or update or delete on public.boletos for each row execute function public.audit_critical_change();
  end if;
end $$;

insert into public.schema_migrations(version, description)
values ('001_20260911', 'Observabilidade, métricas e auditoria de alterações críticas')
on conflict (version) do update set description = excluded.description;

-- =============================================================================
-- 002_20260911_rate_limit_webhook_queue
-- O que: rate limit distribuído e fila durável de webhooks.
-- Por quê: evitar brute force/spam e não perder eventos externos quando um Worker falhar.
-- Quem usa: middleware do Worker e cron do Cloudflare.
-- =============================================================================
create table if not exists public.rate_limit_buckets (
  key text primary key,
  window_started_at timestamptz not null,
  hit_count integer not null default 0 check (hit_count >= 0),
  updated_at timestamptz not null default now()
);
comment on table public.rate_limit_buckets is 'Buckets de rate limit distribuído por IP/usuário. Armazena apenas chaves com hash, nunca IP ou credencial em texto aberto.';
create index if not exists rate_limit_buckets_updated_idx on public.rate_limit_buckets(updated_at);

create or replace function public.check_rate_limit(p_key text, p_limit integer, p_window_seconds integer)
returns table(allowed boolean, remaining integer, retry_after_seconds integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_start timestamptz;
  v_count integer;
  v_window integer := greatest(1, least(coalesce(p_window_seconds, 60), 86400));
  v_limit integer := greatest(1, least(coalesce(p_limit, 60), 10000));
begin
  if p_key is null or char_length(p_key) = 0 or char_length(p_key) > 200 then
    raise exception 'RATE_LIMIT_KEY_INVALID';
  end if;

  insert into public.rate_limit_buckets(key, window_started_at, hit_count, updated_at)
  values (p_key, v_now, 1, v_now)
  on conflict (key) do update
  set window_started_at = case
        when public.rate_limit_buckets.window_started_at + make_interval(secs => v_window) <= v_now then v_now
        else public.rate_limit_buckets.window_started_at
      end,
      hit_count = case
        when public.rate_limit_buckets.window_started_at + make_interval(secs => v_window) <= v_now then 1
        else public.rate_limit_buckets.hit_count + 1
      end,
      updated_at = v_now
  returning window_started_at, hit_count into v_start, v_count;

  allowed := v_count <= v_limit;
  remaining := greatest(0, v_limit - v_count);
  retry_after_seconds := greatest(1, ceil(extract(epoch from (v_start + make_interval(secs => v_window) - v_now)))::integer);
  return next;
end;
$$;
revoke all on function public.check_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.check_rate_limit(text, integer, integer) to service_role;

create table if not exists public.webhook_queue (
  id uuid primary key default gen_random_uuid(),
  provider text not null check (provider in ('rd_station','mercado_pago','conta_azul','brb','bb','santander','sicredi','efi','mock')),
  event_id text not null,
  event_type text not null default 'webhook',
  request_url text not null,
  headers jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pendente' check (status in ('pendente','processando','processado','falhou')),
  attempts integer not null default 0 check (attempts between 0 and 100),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  processed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, event_id)
);
comment on table public.webhook_queue is 'Fila durável e idempotente de webhooks externos. O endpoint somente valida e enfileira; o cron processa com retries e backoff.';
create index if not exists webhook_queue_ready_idx on public.webhook_queue(status, next_attempt_at, created_at) where status = 'pendente';
create index if not exists webhook_queue_provider_idx on public.webhook_queue(provider, created_at desc);

create or replace function public.dequeue_webhook_events(p_limit integer default 25)
returns setof public.webhook_queue
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with picked as (
    select q.id
    from public.webhook_queue q
    where q.status = 'pendente'
      and q.next_attempt_at <= now()
      and (q.locked_at is null or q.locked_at < now() - interval '10 minutes')
    order by q.created_at
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 25), 100))
  )
  update public.webhook_queue q
  set status = 'processando',
      attempts = q.attempts + 1,
      locked_at = now(),
      updated_at = now()
  from picked
  where q.id = picked.id
  returning q.*;
end;
$$;
revoke all on function public.dequeue_webhook_events(integer) from public, anon, authenticated;
grant execute on function public.dequeue_webhook_events(integer) to service_role;

insert into public.schema_migrations(version, description)
values ('002_20260911', 'Rate limit distribuído e fila durável de webhooks')
on conflict (version) do update set description = excluded.description;

-- =============================================================================
-- 003_20260911_soft_delete_indices_constraints
-- O que: soft delete, limites financeiros, índices e integridade complementar.
-- Por quê: preservar audit trail e manter consultas rápidas em crescimento.
-- Quem usa: todos os módulos operacionais via Worker.
-- =============================================================================
do $$
begin
  if to_regclass('public.clientes') is not null then
    alter table public.clientes add column if not exists deleted_at timestamptz;
    alter table public.clientes add column if not exists deleted_by text;
  end if;
  if to_regclass('public.contratos_credito') is not null then
    alter table public.contratos_credito add column if not exists deleted_at timestamptz;
    alter table public.contratos_credito add column if not exists deleted_by text;
    alter table public.contratos_credito drop constraint if exists contratos_credito_valor_contrato_check;
    alter table public.contratos_credito add constraint contratos_credito_valor_contrato_check check (valor_contrato >= 0 and valor_contrato <= 50000000) not valid;
    alter table public.contratos_credito validate constraint contratos_credito_valor_contrato_check;
  end if;
  if to_regclass('public.colaboradores') is not null then
    alter table public.colaboradores add column if not exists deleted_at timestamptz;
    alter table public.colaboradores add column if not exists deleted_by text;
  end if;
  if to_regclass('public.treinamentos') is not null then
    alter table public.treinamentos add column if not exists deleted_at timestamptz;
  end if;
  if to_regclass('public.clube_recompensas') is not null then
    alter table public.clube_recompensas add column if not exists deleted_at timestamptz;
  end if;
end $$;

create index if not exists clientes_ativo_deleted_idx on public.clientes(ativo, deleted_at) where deleted_at is null;
create index if not exists clientes_cpf_active_idx on public.clientes(cpf) where deleted_at is null;
create index if not exists boletos_cliente_status_venc_idx on public.boletos(cliente_id, status, data_vencimento);
create index if not exists boletos_recebido_idx on public.boletos(recebido_em desc) where recebido_em is not null;
create index if not exists boletos_external_charge_idx on public.boletos(external_charge_id) where external_charge_id is not null;
create index if not exists contratos_credito_cliente_created_idx on public.contratos_credito(cliente_id, created_at desc) where deleted_at is null;
create index if not exists contratos_credito_etapa_active_idx on public.contratos_credito(etapa, updated_at desc) where deleted_at is null;
create index if not exists agenda_janelas_tipo_data_status_idx on public.agenda_janelas(tipo, data, status);
create index if not exists agenda_reservas_janela_status_idx on public.agenda_reservas_credito(janela_id, status);
create index if not exists integracao_eventos_provider_created_idx on public.integracao_eventos(provedor, created_at desc);
create index if not exists comprovantes_cliente_status_idx on public.comprovantes_pagamento(cliente_id, status, created_at desc);
create index if not exists indicacoes_indicador_status_idx on public.indicacoes_clientes(indicador_cliente_id, status, created_at desc);
create index if not exists comissao_status_competencia_idx on public.comissao_eventos(status, competencia desc);
create index if not exists treinamento_progresso_colaborador_idx on public.treinamento_progresso(colaborador_id, updated_at desc);

insert into public.schema_migrations(version, description)
values ('003_20260911', 'Soft delete, constraints financeiras e índices de escala')
on conflict (version) do update set description = excluded.description;

-- =============================================================================
-- 004_20260911_rls_e_documentacao
-- O que: RLS deny-by-default e documentação de tabelas do novo domínio.
-- Por quê: browser nunca deve alcançar dados sensíveis; acesso é mediado pelo Worker.
-- Quem usa: service_role no Worker; usuários finais usam somente endpoints autorizados.
-- =============================================================================
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'clientes','boletos','contratos_credito','integracao_vinculos','integracao_eventos',
    'comprovantes_pagamento','conciliacao_financeira_eventos','agenda_janelas','agenda_reservas_credito',
    'clube_recompensas','cliente_pontos','cliente_pontos_eventos','indicacoes_clientes','clube_resgates',
    'colaboradores','comissao_regras','comissao_eventos','treinamentos','treinamento_progresso',
    'audit_log','api_request_metrics','rate_limit_buckets','webhook_queue'
  ] loop
    if to_regclass('public.' || table_name) is not null then
      execute format('alter table public.%I enable row level security', table_name);
      execute format('alter table public.%I force row level security', table_name);
      execute format('revoke all on table public.%I from anon, authenticated', table_name);
    end if;
  end loop;
end $$;

comment on table public.contratos_credito is 'Contrato operacional da cliente, com etapa da jornada, elegibilidade e quitação. Usado por cliente, financeiro e gestão somente via Worker.';
comment on table public.integracao_vinculos is 'Mapeia IDs internos para IDs de RD, bancos, Conta Azul e Mercado Pago. Usado pelos adapters de integração.';
comment on table public.integracao_eventos is 'Histórico idempotente de eventos externos já normalizados. Usado por conciliação, suporte e auditoria.';
comment on table public.comprovantes_pagamento is 'Metadados de comprovantes enviados por clientes. Arquivo fica no Storage; validação é feita pelo financeiro.';
comment on table public.conciliacao_financeira_eventos is 'Trilha de conciliação financeira entre parcela, comprovante e provedor. Usado pelo financeiro e auditoria.';
comment on table public.agenda_janelas is 'Janelas liberadas pela Sra. Luck para termos e cirurgia, com vagas e status. Usada por cliente e gestão via Worker.';
comment on table public.agenda_reservas_credito is 'Reserva de uma janela para um contrato de crédito. Preserva histórico de reagendamentos e cancelamentos.';
comment on table public.clube_recompensas is 'Catálogo de mimos e experiências do Clube de Vantagens. Gerenciado pela administração e exibido no app da cliente.';
comment on table public.cliente_pontos is 'Saldo atual de pontos da cliente. Mantido junto ao histórico imutável de eventos de pontos.';
comment on table public.cliente_pontos_eventos is 'Razão de pontos da cliente: indicação, bônus, resgate ou ajuste. Usado para auditoria do Clube.';
comment on table public.indicacoes_clientes is 'Indicações feitas por clientes e estágio de validação comercial. Origina pontos somente após regra validada.';
comment on table public.clube_resgates is 'Solicitações e entregas de recompensas do Clube de Vantagens. Usado por cliente e operação.';
comment on table public.colaboradores is 'Perfis de vendedora, SDR, financeiro, gestão e admin vinculados ao Auth. Usado no PWA da equipe.';
comment on table public.comissao_regras is 'Regras versionáveis de comissão por perfil. Alteradas pela administração sem mudança de código.';
comment on table public.comissao_eventos is 'Lançamentos de comissão previstos, validados, pagos ou cancelados por colaborador e competência.';
comment on table public.treinamentos is 'Conteúdos de treinamento em vídeo, imagem, texto ou misto destinados a perfis da equipe.';
comment on table public.treinamento_progresso is 'Progresso individual do colaborador em cada treinamento.';

insert into public.schema_migrations(version, description)
values ('004_20260911', 'RLS deny-by-default e documentação do domínio')
on conflict (version) do update set description = excluded.description;

commit;
