-- ============================================================================
-- MIGRATION 092: Régua de parcelas unificada e catálogo de templates
-- ============================================================================
-- Regras (worker/admin-notificacoes.ts + worker/notificacao-templates-padrao.ts):
--   * uma notificação por cliente por rodada, com todas as parcelas em aberto;
--   * titulo/corpo para 1 parcela, titulo_multiplas/corpo_multiplas para 2+;
--   * atraso: um texto por dia de 1 a 30; 31 = texto único para 31+ dias;
--   * D-2, D-1 e D0 antes do vencimento.
-- Os textos abaixo são gerados de worker/notificacao-templates-padrao.ts.
--
-- Não destrutiva: os templates de parcela anteriores (inclusive duplicados)
-- ficam copiados em notificacao_templates_backup_092.
-- Rollback: apagar as linhas parcela_vencer/parcela_atrasada, reinserir a
-- partir do backup e remover o índice ux_notificacao_templates_regua.

create table if not exists notificacao_templates_backup_092 as
  select * from notificacao_templates where tipo in ('parcela_vencer', 'parcela_atrasada');
alter table notificacao_templates_backup_092 enable row level security;

alter table notificacao_templates add column if not exists titulo_multiplas text;
alter table notificacao_templates add column if not exists corpo_multiplas text;

delete from notificacao_templates where tipo in ('parcela_vencer', 'parcela_atrasada');

create unique index if not exists ux_notificacao_templates_regua
  on notificacao_templates (tipo, dias_referencia)
  where tipo in ('parcela_vencer', 'parcela_atrasada');

insert into notificacao_templates (tipo, dias_referencia, titulo, corpo, titulo_multiplas, corpo_multiplas, emoji, is_active) values
  ('parcela_vencer', 2, 'Sua parcela vence em 2 dias', '{{nome}}, a parcela {{parcela}}/{{total}} de {{valor}} vence em {{vencimento}}. Pague pelo app e siga tranquila.', 'Suas parcelas vencem em breve', '{{nome}}, você tem {{quantidade}} parcelas vencendo nos próximos dias, somando {{valor_total}}. Organize tudo pelo app em poucos toques.', '🗓️', true),
  ('parcela_vencer', 1, 'Sua parcela vence amanhã', '{{nome}}, amanhã ({{vencimento}}) vence a parcela {{parcela}}/{{total}} de {{valor}}. Se preferir, já deixe paga hoje pelo app.', 'Parcelas vencendo amanhã', '{{nome}}, amanhã vencem {{quantidade}} parcelas, somando {{valor_total}}. Pagando pelo app, sua jornada continua em dia.', '⏰', true),
  ('parcela_vencer', 0, 'Sua parcela vence hoje', '{{nome}}, hoje é o vencimento da parcela {{parcela}}/{{total}} de {{valor}}. Pelo app você paga em segundos com PIX.', 'Suas parcelas vencem hoje', '{{nome}}, hoje vencem {{quantidade}} parcelas, somando {{valor_total}}. Resolva tudo de uma vez pelo app.', '💳', true),
  ('parcela_atrasada', 1, 'Sua parcela venceu ontem', '{{nome}}, a parcela {{parcela}}/{{total}} venceu ontem. Às vezes passa, acontece! Pague pelo app e o valor atualizado já aparece para você.', 'Parcelas em aberto', '{{nome}}, você tem {{quantidade}} parcelas em aberto, a mais antiga venceu em {{vencimento}}. Regularize tudo de uma vez pelo app.', '🔔', true),
  ('parcela_atrasada', 2, 'Ainda dá tempo de resolver hoje', '{{nome}}, a parcela {{parcela}}/{{total}} está em aberto há 2 dias. É rapidinho pelo app.', 'Suas parcelas seguem em aberto', '{{nome}}, {{quantidade}} parcelas seguem em aberto, somando {{valor_total}}. Pelo app você vê o valor atualizado e paga na hora.', '🔔', true),
  ('parcela_atrasada', 3, 'Podemos ajudar com sua parcela?', '{{nome}}, sua parcela {{parcela}}/{{total}} está há 3 dias em aberto. Se já pagou, envie o comprovante pelo app. Se não, dá para resolver agora.', 'Podemos ajudar com suas parcelas?', '{{nome}}, há {{quantidade}} parcelas em aberto no seu plano. Se já pagou, envie os comprovantes pelo app. Se não, resolva em poucos toques.', '💬', true),
  ('parcela_atrasada', 4, 'Sua parcela continua em aberto', '{{nome}}, a parcela {{parcela}}/{{total}} venceu em {{vencimento}}. Manter o plano em dia é o que aproxima a sua cirurgia. Resolva pelo app.', 'Suas parcelas continuam em aberto', '{{nome}}, {{quantidade}} parcelas continuam em aberto. Manter o plano em dia é o que aproxima a sua cirurgia. Resolva tudo pelo app.', '💬', true),
  ('parcela_atrasada', 5, 'Um lembrete com carinho', '{{nome}}, sua parcela {{parcela}}/{{total}} está há 5 dias em aberto. Estamos aqui se precisar de ajuda: é só chamar a nossa equipe.', 'Um lembrete com carinho', '{{nome}}, suas {{quantidade}} parcelas em aberto somam {{valor_total}}. Estamos aqui se precisar de ajuda: é só chamar a nossa equipe.', '💬', true),
  ('parcela_atrasada', 6, 'Sua parcela precisa de atenção', '{{nome}}, a parcela {{parcela}}/{{total}} está em aberto há 6 dias. O valor atualizado está no app, pronto para pagar.', 'Suas parcelas precisam de atenção', '{{nome}}, {{quantidade}} parcelas estão em aberto e a mais antiga já tem 6 dias. O valor atualizado está no app.', '📌', true),
  ('parcela_atrasada', 7, 'Uma semana de parcela em aberto', '{{nome}}, faz uma semana que a parcela {{parcela}}/{{total}} venceu. Vamos colocar em dia? Pelo app leva menos de um minuto.', 'Uma semana de parcelas em aberto', '{{nome}}, a mais antiga das suas {{quantidade}} parcelas em aberto venceu há uma semana. Vamos colocar tudo em dia pelo app?', '📌', true),
  ('parcela_atrasada', 8, 'Sua parcela segue pendente', '{{nome}}, a parcela {{parcela}}/{{total}} segue pendente há {{dias_atraso}} dias. Se algo aconteceu, fale com a gente pelo WhatsApp.', 'Suas parcelas seguem pendentes', '{{nome}}, {{quantidade}} parcelas seguem pendentes, somando {{valor_total}}. Se algo aconteceu, fale com a gente pelo WhatsApp.', '📌', true),
  ('parcela_atrasada', 9, 'Vamos resolver juntas?', '{{nome}}, sua parcela {{parcela}}/{{total}} está há {{dias_atraso}} dias em aberto. Nossa equipe pode te orientar no melhor caminho.', 'Vamos resolver juntas?', '{{nome}}, suas {{quantidade}} parcelas em aberto já passam de uma semana. Nossa equipe pode te orientar no melhor caminho.', '📌', true),
  ('parcela_atrasada', 10, '10 dias de parcela em aberto', '{{nome}}, a parcela {{parcela}}/{{total}} completa 10 dias em aberto. Regularize pelo app para manter sua jornada caminhando.', '10 dias de parcelas em aberto', '{{nome}}, a parcela mais antiga das suas {{quantidade}} em aberto completa 10 dias. Regularize pelo app para manter sua jornada caminhando.', '📌', true),
  ('parcela_atrasada', 11, 'Sua parcela ainda está em aberto', '{{nome}}, a parcela {{parcela}}/{{total}} venceu em {{vencimento}} e ainda está em aberto. Se já pagou, envie o comprovante pelo app.', 'Suas parcelas ainda estão em aberto', '{{nome}}, {{quantidade}} parcelas ainda estão em aberto no seu plano. Se já pagou alguma, envie o comprovante pelo app.', '📌', true),
  ('parcela_atrasada', 12, 'Seu plano precisa de você', '{{nome}}, sua parcela {{parcela}}/{{total}} está há {{dias_atraso}} dias em aberto. Cada parcela paga conta para liberar sua agenda.', 'Seu plano precisa de você', '{{nome}}, você tem {{quantidade}} parcelas em aberto. Cada parcela paga conta para liberar sua agenda. Resolva pelo app.', '📌', true),
  ('parcela_atrasada', 13, 'Lembrete da sua parcela', '{{nome}}, a parcela {{parcela}}/{{total}} segue em aberto há {{dias_atraso}} dias. O valor atualizado está no app, com PIX na hora.', 'Lembrete das suas parcelas', '{{nome}}, suas {{quantidade}} parcelas em aberto somam {{valor_total}}. O valor atualizado está no app, com PIX na hora.', '📌', true),
  ('parcela_atrasada', 14, 'Duas semanas de parcela em aberto', '{{nome}}, sua parcela {{parcela}}/{{total}} está em aberto há duas semanas. Queremos te ajudar: fale com a nossa equipe ou resolva pelo app.', 'Duas semanas de parcelas em aberto', '{{nome}}, a mais antiga das suas {{quantidade}} parcelas em aberto já tem duas semanas. Fale com a nossa equipe ou resolva pelo app.', '🤝', true),
  ('parcela_atrasada', 15, 'Precisamos falar da sua parcela', '{{nome}}, a parcela {{parcela}}/{{total}} está há {{dias_atraso}} dias em aberto. Conte com a gente para encontrar o melhor caminho.', 'Precisamos falar das suas parcelas', '{{nome}}, {{quantidade}} parcelas estão em aberto há mais de duas semanas. Conte com a gente para encontrar o melhor caminho.', '🤝', true),
  ('parcela_atrasada', 16, 'Sua parcela segue em aberto', '{{nome}}, a parcela {{parcela}}/{{total}} continua pendente. Colocar em dia mantém sua jornada rumo à cirurgia. Resolva pelo app.', 'Suas parcelas seguem em aberto', '{{nome}}, {{quantidade}} parcelas continuam pendentes, somando {{valor_total}}. Colocar em dia mantém sua jornada rumo à cirurgia.', '🤝', true),
  ('parcela_atrasada', 17, 'Estamos aqui por você', '{{nome}}, sabemos que imprevistos acontecem. Sua parcela {{parcela}}/{{total}} está há {{dias_atraso}} dias em aberto: chame a gente.', 'Estamos aqui por você', '{{nome}}, sabemos que imprevistos acontecem. Você tem {{quantidade}} parcelas em aberto: chame a nossa equipe para conversar.', '🤝', true),
  ('parcela_atrasada', 18, 'Sua parcela pede atenção', '{{nome}}, a parcela {{parcela}}/{{total}} está há {{dias_atraso}} dias em aberto. Pague pelo app ou fale com a equipe.', 'Suas parcelas pedem atenção', '{{nome}}, suas {{quantidade}} parcelas em aberto já passam de duas semanas. Pague pelo app ou fale com a equipe.', '🤝', true),
  ('parcela_atrasada', 19, 'Vamos colocar seu plano em dia?', '{{nome}}, sua parcela {{parcela}}/{{total}} venceu em {{vencimento}}. Um passo de cada vez: comece por ela pelo app.', 'Vamos colocar seu plano em dia?', '{{nome}}, são {{quantidade}} parcelas em aberto. Um passo de cada vez: comece pela mais antiga, direto pelo app.', '🤝', true),
  ('parcela_atrasada', 20, '20 dias de parcela em aberto', '{{nome}}, a parcela {{parcela}}/{{total}} completa 20 dias em aberto. Nossa equipe está disponível para te orientar.', '20 dias de parcelas em aberto', '{{nome}}, a mais antiga das suas {{quantidade}} parcelas em aberto completa 20 dias. Nossa equipe está disponível para te orientar.', '🤝', true),
  ('parcela_atrasada', 21, 'Três semanas de parcela em aberto', '{{nome}}, sua parcela {{parcela}}/{{total}} está em aberto há três semanas. Vamos resolver juntas? Fale com a nossa equipe.', 'Três semanas de parcelas em aberto', '{{nome}}, você tem {{quantidade}} parcelas em aberto e a mais antiga já tem três semanas. Vamos resolver juntas?', '🤝', true),
  ('parcela_atrasada', 22, 'Sua parcela precisa ser regularizada', '{{nome}}, a parcela {{parcela}}/{{total}} está há {{dias_atraso}} dias em aberto. Regularize pelo app ou fale com a nossa equipe.', 'Suas parcelas precisam ser regularizadas', '{{nome}}, {{quantidade}} parcelas estão em aberto, somando {{valor_total}}. Regularize pelo app ou fale com a nossa equipe.', '⚠️', true),
  ('parcela_atrasada', 23, 'Precisamos da sua atenção', '{{nome}}, sua parcela {{parcela}}/{{total}} segue em aberto há {{dias_atraso}} dias. Se já pagou, envie o comprovante pelo app.', 'Precisamos da sua atenção', '{{nome}}, suas {{quantidade}} parcelas seguem em aberto. Se já pagou alguma, envie o comprovante pelo app para conferirmos.', '⚠️', true),
  ('parcela_atrasada', 24, 'Sua parcela continua pendente', '{{nome}}, a parcela {{parcela}}/{{total}} continua pendente. Manter o plano em dia é o que garante o avanço da sua jornada.', 'Suas parcelas continuam pendentes', '{{nome}}, {{quantidade}} parcelas continuam pendentes. Manter o plano em dia é o que garante o avanço da sua jornada.', '⚠️', true),
  ('parcela_atrasada', 25, 'Vamos conversar sobre sua parcela?', '{{nome}}, sua parcela {{parcela}}/{{total}} está há {{dias_atraso}} dias em aberto. Chame a nossa equipe para entender o melhor caminho.', 'Vamos conversar sobre suas parcelas?', '{{nome}}, você tem {{quantidade}} parcelas em aberto. Chame a nossa equipe para entender o melhor caminho para colocar tudo em dia.', '⚠️', true),
  ('parcela_atrasada', 26, 'Parcela aguardando pagamento', '{{nome}}, a parcela {{parcela}}/{{total}} venceu em {{vencimento}} e segue em aberto. O valor atualizado está no app.', 'Parcelas aguardando pagamento', '{{nome}}, {{quantidade}} parcelas seguem em aberto, somando {{valor_total}} sem encargos. O valor atualizado está no app.', '⚠️', true),
  ('parcela_atrasada', 27, 'Lembrete importante da sua parcela', '{{nome}}, sua parcela {{parcela}}/{{total}} está há {{dias_atraso}} dias em aberto. Resolva pelo app ou fale com a equipe.', 'Lembrete importante das suas parcelas', '{{nome}}, suas {{quantidade}} parcelas em aberto precisam de atenção. Resolva pelo app ou fale com a nossa equipe.', '⚠️', true),
  ('parcela_atrasada', 28, 'Quatro semanas de parcela em aberto', '{{nome}}, a parcela {{parcela}}/{{total}} está em aberto há quatro semanas. Estamos aqui para te ajudar a colocar em dia.', 'Quatro semanas de parcelas em aberto', '{{nome}}, a mais antiga das suas {{quantidade}} parcelas em aberto já tem quatro semanas. Estamos aqui para te ajudar.', '⚠️', true),
  ('parcela_atrasada', 29, 'Sua parcela precisa de você', '{{nome}}, a parcela {{parcela}}/{{total}} segue pendente há {{dias_atraso}} dias. Pague pelo app ou chame a nossa equipe.', 'Suas parcelas precisam de você', '{{nome}}, {{quantidade}} parcelas seguem pendentes. Pague pelo app ou chame a nossa equipe para conversar.', '⚠️', true),
  ('parcela_atrasada', 30, 'Um mês de parcela em aberto', '{{nome}}, sua parcela {{parcela}}/{{total}} completa um mês em aberto. Fale com a nossa equipe para regularizar o seu plano.', 'Um mês de parcelas em aberto', '{{nome}}, a mais antiga das suas {{quantidade}} parcelas em aberto completa um mês. Fale com a nossa equipe para regularizar o plano.', '⚠️', true),
  ('parcela_atrasada', 31, 'Seu plano tem parcela em aberto', '{{nome}}, a parcela {{parcela}}/{{total}} está em aberto há {{dias_atraso}} dias. Regularize pelo app ou fale com a nossa equipe.', 'Seu plano tem {{quantidade}} parcelas em aberto', '{{nome}}, seu plano tem {{quantidade}} parcelas em aberto, somando {{valor_total}} sem encargos. Regularize pelo app ou fale com a nossa equipe.', '📋', true);

insert into notificacoes_config (chave, valor, tipo, descricao) values
  ('atraso_recorrente_intervalo_dias', '1', 'number', 'Intervalo em dias entre avisos para atrasos de 31 dias ou mais')
on conflict (chave) do nothing;
