import { NextRequest, NextResponse } from "next/server";
import { createServerSupabaseClient } from "@/lib/supabase/server";

const CAMPO_LABEL: Record<string, string> = { nome_completo: "Nome completo", telefone: "Telefone", email: "E-mail", procedimento: "Procedimento", valor_contrato: "Carta de crédito", taxa_administrativa_percentual: "Taxa administrativa (%)", ativo: "Ativa", observacoes_internas: "Observações" };

export async function GET(_req: NextRequest, { params }: { params: { id: string } }) { const supabase = createServerSupabaseClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return NextResponse.json({ erro: "Não autenticado." }, { status: 401 }); const { data: cliente, error } = await supabase.from("clientes").select("*").eq("id", params.id).single(); if (error) return NextResponse.json({ erro: error.message }, { status: 404 }); const { data: historico } = await supabase.from("logs_alteracoes").select("*").eq("entidade", "clientes").eq("entidade_id", params.id).order("created_at", { ascending: false }); return NextResponse.json({ cliente, historico: historico ?? [] }); }

export async function PATCH(req: NextRequest, { params }: { params: { id: string } }) {
 const supabase = createServerSupabaseClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return NextResponse.json({ erro: "Não autenticado." }, { status: 401 }); const body = await req.json(); const atualizacoes: Record<string, unknown> = {};
 if (body.nomeCompleto !== undefined) atualizacoes.nome_completo = body.nomeCompleto; if (body.telefone !== undefined) atualizacoes.telefone = body.telefone || null; if (body.email !== undefined) atualizacoes.email = body.email || null; if (body.procedimento !== undefined) atualizacoes.procedimento = body.procedimento || null;
 if (body.valorContrato !== undefined) { const valor = Number(body.valorContrato); if (!Number.isFinite(valor) || valor <= 0) return NextResponse.json({ erro: "Carta de crédito inválida." }, { status: 400 }); atualizacoes.valor_contrato = valor; }
 if (body.taxaAdministrativaPercentual !== undefined) { const taxa = Number(body.taxaAdministrativaPercentual); if (!Number.isFinite(taxa) || taxa < 0) return NextResponse.json({ erro: "Taxa administrativa inválida." }, { status: 400 }); atualizacoes.taxa_administrativa_percentual = taxa; }
 if (body.ativo !== undefined) atualizacoes.ativo = body.ativo; if (body.observacoes !== undefined) atualizacoes.observacoes_internas = body.observacoes || null;
 if (Object.keys(atualizacoes).length === 0 && body.valorParcela === undefined) return NextResponse.json({ erro: "Nenhuma alteração informada." }, { status: 400 });
 const { data: anterior } = await supabase.from("clientes").select("*").eq("id", params.id).single(); if (!anterior) return NextResponse.json({ erro: "Cliente não encontrada." }, { status: 404 });
 const { data, error } = Object.keys(atualizacoes).length ? await supabase.from("clientes").update(atualizacoes).eq("id", params.id).select("*").single() : await supabase.from("clientes").select("*").eq("id", params.id).single(); if (error) return NextResponse.json({ erro: error.message }, { status: 400 });
 if (body.recalcularBoletosAbertos && (atualizacoes.valor_contrato !== undefined || atualizacoes.taxa_administrativa_percentual !== undefined || body.valorParcela !== undefined)) { const carta = Number(data.valor_contrato); const taxa = Number(data.taxa_administrativa_percentual ?? 0); const quantidade = Number(data.quantidade_parcelas ?? 0); if (quantidade > 0) { const informado = Number(body.valorParcela); const valorParcela = Number.isFinite(informado) && informado > 0 ? Number(informado.toFixed(2)) : Number(((carta * (1 + taxa / 100)) / quantidade).toFixed(2)); const { error: erroBoletos } = await supabase.from("boletos").update({ valor: valorParcela }).eq("cliente_id", params.id).neq("status", "pago"); if (erroBoletos) return NextResponse.json({ erro: erroBoletos.message }, { status: 500 }); try { await supabase.channel(`notificacoes-cliente:${params.id}`).send({ type: "broadcast", event: "nova_notificacao", payload: { tipo: "credito_atualizado", quantidadeParcelas: quantidade } }); } catch (erro) { console.error("Falha no realtime do cliente:", erro); } } }
 const alteracoes = Object.keys(atualizacoes).filter((campo) => anterior[campo] !== atualizacoes[campo]).map((campo) => ({ campo: CAMPO_LABEL[campo] ?? campo, de: anterior[campo], para: atualizacoes[campo] })); if (body.valorParcela !== undefined) alteracoes.push({ campo: "Valor da parcela", de: null, para: Number(body.valorParcela) }); if (alteracoes.length > 0) await supabase.from("logs_alteracoes").insert({ usuario: user.email ?? "admin", acao: "editou_cliente", entidade: "clientes", entidade_id: params.id, detalhes: { cliente: data.nome_completo, alteracoes } }); return NextResponse.json({ cliente: data });
}

export async function DELETE(_req: NextRequest, { params }: { params: { id: string } }) { const supabase = createServerSupabaseClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return NextResponse.json({ erro: "Não autenticado." }, { status: 401 }); const { data: cliente } = await supabase.from("clientes").select("nome_completo").eq("id", params.id).single(); const { error } = await supabase.from("clientes").delete().eq("id", params.id); if (error) return NextResponse.json({ erro: error.message }, { status: 400 }); await supabase.from("logs_alteracoes").insert({ usuario: user.email ?? "admin", acao: "removeu_cliente", entidade: "clientes", entidade_id: params.id, detalhes: { cliente: cliente?.nome_completo ?? null } }); return NextResponse.json({ ok: true }); }
