alter table public.agenda_sync_state add constraint agenda_sync_state_pkey PRIMARY KEY (tipo);
alter table public.agendamentos add constraint agendamentos_pkey PRIMARY KEY (id);
alter table public.boletos add constraint boletos_pkey PRIMARY KEY (id);
alter table public.carne_importacoes add constraint carne_importacoes_pkey PRIMARY KEY (id);
alter table public.carnes add constraint carnes_pkey PRIMARY KEY (id);
alter table public.cliente_app_devices add constraint cliente_app_devices_pkey PRIMARY KEY (id);
alter table public.cliente_pontos add constraint cliente_pontos_pkey PRIMARY KEY (cliente_id);
alter table public.cliente_pontos_eventos add constraint cliente_pontos_eventos_pkey PRIMARY KEY (id);
alter table public.clientes add constraint clientes_pkey PRIMARY KEY (id);
alter table public.clube_beneficios_cliente add constraint clube_beneficios_cliente_pkey PRIMARY KEY (id);
alter table public.clube_campanhas add constraint clube_campanhas_pkey PRIMARY KEY (id);
alter table public.clube_config add constraint clube_config_pkey PRIMARY KEY (id);
alter table public.clube_recompensas add constraint clube_recompensas_pkey PRIMARY KEY (id);
alter table public.clube_resgates add constraint clube_resgates_pkey PRIMARY KEY (id);
alter table public.colaboradores add constraint colaboradores_pkey PRIMARY KEY (id);
alter table public.comissao_eventos add constraint comissao_eventos_pkey PRIMARY KEY (id);
alter table public.comissao_regras add constraint comissao_regras_pkey PRIMARY KEY (id);
alter table public.comissoes add constraint comissoes_pkey PRIMARY KEY (id);
alter table public.conciliacao_pagamentos add constraint conciliacao_pagamentos_pkey PRIMARY KEY (id);
alter table public.conciliacao_pagamentos_historico add constraint conciliacao_pagamentos_historico_pkey PRIMARY KEY (id);
alter table public.configuracoes add constraint configuracoes_pkey PRIMARY KEY (id);
alter table public.conta_azul_vinculos add constraint conta_azul_vinculos_pkey PRIMARY KEY (id);
alter table public.crm_vendas_entrada add constraint crm_vendas_entrada_pkey PRIMARY KEY (id);
alter table public.datas add constraint datas_pkey PRIMARY KEY (id);
alter table public.datas_liberacao_financeira add constraint datas_liberacao_financeira_pkey PRIMARY KEY (id);
alter table public.feedback_jornada add constraint feedback_jornada_pkey PRIMARY KEY (id);
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_pkey PRIMARY KEY (id);
alter table public.frases_do_dia add constraint frases_do_dia_pkey PRIMARY KEY (id);
alter table public.home_campanhas_config add constraint home_campanhas_config_pkey PRIMARY KEY (id);
alter table public.importacoes_boletos add constraint importacoes_boletos_pkey PRIMARY KEY (id);
alter table public.indicacoes_clientes add constraint indicacoes_clientes_pkey PRIMARY KEY (id);
alter table public.integracao_conflitos add constraint integracao_conflitos_pkey PRIMARY KEY (id);
alter table public.integracao_cursores add constraint integracao_cursores_pkey PRIMARY KEY (provedor, nome);
alter table public.integracao_eventos add constraint integracao_eventos_pkey PRIMARY KEY (id);
alter table public.integracao_fila add constraint integracao_fila_pkey PRIMARY KEY (id);
alter table public.integracao_importacao_itens add constraint integracao_importacao_itens_pkey PRIMARY KEY (id);
alter table public.integracao_importacoes add constraint integracao_importacoes_pkey PRIMARY KEY (id);
alter table public.integracao_travas add constraint integracao_travas_pkey PRIMARY KEY (nome);
alter table public.integracao_uso add constraint integracao_uso_pkey PRIMARY KEY (provedor, funcao, dia);
alter table public.integracoes_config add constraint integracoes_config_pkey PRIMARY KEY (provedor, funcao);
alter table public.integracoes_credenciais add constraint integracoes_credenciais_pkey PRIMARY KEY (id);
alter table public.integracoes_estado add constraint integracoes_estado_pkey PRIMARY KEY (provedor);
alter table public.login_rate_limits add constraint login_rate_limits_pkey PRIMARY KEY (chave);
alter table public.logs_alteracoes add constraint logs_alteracoes_pkey PRIMARY KEY (id);
alter table public.mensagens_do_dia add constraint mensagens_do_dia_pkey PRIMARY KEY (data);
alter table public.mensagens_motivacionais add constraint mensagens_motivacionais_pkey PRIMARY KEY (id);
alter table public.metas_colaboradores add constraint metas_colaboradores_pkey PRIMARY KEY (id);
alter table public.monitoramento_acessos add constraint monitoramento_acessos_pkey PRIMARY KEY (id);
alter table public.monitoramento_erros add constraint monitoramento_erros_pkey PRIMARY KEY (id);
alter table public.notificacao_agendadas add constraint notificacao_agendadas_pkey PRIMARY KEY (id);
alter table public.notificacao_eventos add constraint notificacao_eventos_pkey PRIMARY KEY (chave);
alter table public.notificacao_logs add constraint notificacao_logs_pkey PRIMARY KEY (id);
alter table public.notificacao_lote_itens add constraint notificacao_lote_itens_pkey PRIMARY KEY (id);
alter table public.notificacao_lotes add constraint notificacao_lotes_pkey PRIMARY KEY (id);
alter table public.notificacao_templates add constraint notificacao_templates_pkey PRIMARY KEY (id);
alter table public.notificacoes_cliente add constraint notificacoes_cliente_pkey PRIMARY KEY (id);
alter table public.notificacoes_colaboradores add constraint notificacoes_colaboradores_pkey PRIMARY KEY (id);
alter table public.notificacoes_config add constraint notificacoes_config_pkey PRIMARY KEY (id);
alter table public.novas_vendas add constraint novas_vendas_pkey PRIMARY KEY (id);
alter table public.pagamentos_externos add constraint pagamentos_externos_pkey PRIMARY KEY (id);
alter table public.push_tokens add constraint push_tokens_pkey PRIMARY KEY (id);
alter table public.regras_operacionais add constraint regras_operacionais_pkey PRIMARY KEY (id);
alter table public.relatorios_exportacoes add constraint relatorios_exportacoes_pkey PRIMARY KEY (id);
alter table public.solicitacoes_liberacao_financeira add constraint solicitacoes_liberacao_financeira_pkey PRIMARY KEY (id);
alter table public.solicitacoes_remarcacao_agendamento add constraint solicitacoes_remarcacao_agendamento_pkey PRIMARY KEY (id);
alter table public.treinamento_progresso add constraint treinamento_progresso_pkey PRIMARY KEY (treinamento_id, colaborador_id);
alter table public.treinamentos add constraint treinamentos_pkey PRIMARY KEY (id);
alter table public.web_push_subscriptions add constraint web_push_subscriptions_pkey PRIMARY KEY (id);
alter table public.carne_importacoes add constraint carne_importacoes_chave_unica UNIQUE (chave_idempotencia);
alter table public.cliente_app_devices add constraint cliente_app_devices_cliente_id_device_key_key UNIQUE (cliente_id, device_key);
alter table public.clube_beneficios_cliente add constraint clube_beneficios_cliente_cliente_id_beneficio_key_origem_key UNIQUE (cliente_id, beneficio_key, origem);
alter table public.clube_campanhas add constraint clube_campanhas_chave_key UNIQUE (chave);
alter table public.colaboradores add constraint colaboradores_auth_user_id_key UNIQUE (auth_user_id);
alter table public.comissoes add constraint comissoes_chave_evento_key UNIQUE (chave_evento);
alter table public.conta_azul_vinculos add constraint conta_azul_vinculos_boleto_id_key UNIQUE (boleto_id);
alter table public.conta_azul_vinculos add constraint conta_azul_vinculos_ca_parcela_id_key UNIQUE (ca_parcela_id);
alter table public.conta_azul_vinculos add constraint conta_azul_vinculos_marcador_key UNIQUE (marcador);
alter table public.datas add constraint datas_data_key UNIQUE (data);
alter table public.datas_liberacao_financeira add constraint datas_liberacao_financeira_data_key UNIQUE (data);
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_idempotency_key_key UNIQUE (idempotency_key);
alter table public.frases_do_dia add constraint frases_do_dia_data_segmento_key UNIQUE (data, segmento);
alter table public.integracao_fila add constraint integracao_fila_chave_idempotencia_key UNIQUE (chave_idempotencia);
alter table public.integracoes_credenciais add constraint integracoes_credenciais_provedor_chave_key UNIQUE (provedor, chave);
alter table public.metas_colaboradores add constraint metas_colaboradores_colaborador_id_ano_mes_key UNIQUE (colaborador_id, ano, mes);
alter table public.notificacao_lote_itens add constraint notificacao_lote_itens_lote_id_cliente_id_key UNIQUE (lote_id, cliente_id);
alter table public.notificacoes_config add constraint notificacoes_config_chave_key UNIQUE (chave);
alter table public.novas_vendas add constraint novas_vendas_rd_station_id_key UNIQUE (rd_station_id);
alter table public.pagamentos_externos add constraint pagamentos_externos_provedor_external_payment_id_key UNIQUE (provedor, external_payment_id);
alter table public.push_tokens add constraint push_tokens_cliente_id_token_key UNIQUE (cliente_id, token);
alter table public.push_tokens add constraint push_tokens_token_key UNIQUE (token);
alter table public.solicitacoes_remarcacao_agendamento add constraint solicitacoes_remarcacao_agendamento_agendamento_id_tipo_key UNIQUE (agendamento_id, tipo);
alter table public.web_push_subscriptions add constraint web_push_subscriptions_endpoint_key UNIQUE (endpoint);
alter table public.agenda_sync_state add constraint agenda_sync_state_tipo_check CHECK ((tipo = ANY (ARRAY['termos'::text, 'cirurgia'::text])));
alter table public.agendamentos add constraint agendamentos_comparecimento_status_check CHECK ((comparecimento_status = ANY (ARRAY['pendente'::text, 'compareceu'::text, 'nao_compareceu'::text])));
alter table public.agendamentos add constraint agendamentos_prazo_ajuste_check CHECK ((agenda_cirurgica_prazo_ajuste_dias >= 0));
alter table public.agendamentos add constraint agendamentos_quitacao_status_check CHECK ((quitacao_status = ANY (ARRAY['pendente'::text, 'paga'::text, 'nao_realizada'::text])));
alter table public.boletos add constraint boletos_origem_boleto_chk CHECK ((origem_boleto = ANY (ARRAY['sistema'::text, 'externo'::text])));
alter table public.boletos add constraint chk_numero_parcela CHECK (((numero_parcela > 0) AND (numero_parcela <= total_parcelas)));
alter table public.carne_importacoes add constraint carne_importacoes_arquivo_sha256_check CHECK ((arquivo_sha256 ~ '^[0-9a-f]{64}$'::text));
alter table public.carne_importacoes add constraint carne_importacoes_arquivo_tamanho_check CHECK (((arquivo_tamanho IS NULL) OR (arquivo_tamanho >= 0)));
alter table public.carne_importacoes add constraint carne_importacoes_arquivo_tipo_check CHECK ((arquivo_tipo = ANY (ARRAY['application/pdf'::text, 'image/jpeg'::text, 'image/png'::text])));
alter table public.carne_importacoes add constraint carne_importacoes_nivel_confianca_check CHECK ((nivel_confianca = ANY (ARRAY['ALTA'::text, 'MEDIA'::text, 'BAIXA'::text])));
alter table public.carne_importacoes add constraint carne_importacoes_paginas_check CHECK (((paginas IS NULL) OR (paginas >= 0)));
alter table public.carne_importacoes add constraint carne_importacoes_status_check CHECK ((status = 'concluida'::text));
alter table public.carne_importacoes add constraint carne_importacoes_tipo_documento_check CHECK ((tipo_documento = ANY (ARRAY['PDF_TEXT'::text, 'PDF_SCANNED'::text, 'IMAGE'::text, 'MIXED_PDF'::text])));
alter table public.carnes add constraint carnes_identificador_chk CHECK ((length(TRIM(BOTH FROM identificador_externo)) > 0));
alter table public.carnes add constraint carnes_instituicao_chk CHECK ((length(TRIM(BOTH FROM instituicao_financeira)) > 0));
alter table public.carnes add constraint carnes_quantidade_parcelas_check CHECK ((quantidade_parcelas > 0));
alter table public.carnes add constraint carnes_valor_parcela_check CHECK ((valor_parcela >= (0)::numeric));
alter table public.carnes add constraint carnes_valor_total_check CHECK ((valor_total >= (0)::numeric));
alter table public.cliente_pontos add constraint cliente_pontos_saldo_check CHECK ((saldo >= 0));
alter table public.cliente_pontos_eventos add constraint cliente_pontos_eventos_tipo_check CHECK ((tipo = ANY (ARRAY['indicacao'::text, 'bonus'::text, 'resgate'::text, 'ajuste'::text])));
alter table public.clientes add constraint clientes_dia_cobranca_check CHECK (((dia_cobranca IS NULL) OR ((dia_cobranca >= 1) AND (dia_cobranca <= 31))));
alter table public.clientes add constraint clientes_origem_cadastro_chk CHECK ((origem_cadastro = ANY (ARRAY['manual'::text, 'rd_station'::text])));
alter table public.clientes add constraint clientes_status_plano_check CHECK (((status_plano IS NULL) OR (status_plano = ANY (ARRAY['Ativa'::text, 'Suspensa'::text]))));
alter table public.clube_beneficios_cliente add constraint clube_beneficios_cliente_status_check CHECK ((status = ANY (ARRAY['disponivel'::text, 'utilizado'::text, 'cancelado'::text])));
alter table public.clube_campanhas add constraint clube_campanhas_tipo_check CHECK ((tipo = ANY (ARRAY['primeira_parcela'::text, 'parcela_em_dia'::text, 'indicacao'::text, 'resgate'::text, 'informativa'::text])));
alter table public.clube_campanhas add constraint clube_campanhas_titulo_check CHECK (((length(btrim(titulo)) >= 2) AND (length(btrim(titulo)) <= 120)));
alter table public.clube_config add constraint chk_clube_config_pontos_indicacao_venda CHECK ((pontos_indicacao_venda >= 0));
alter table public.clube_config add constraint chk_clube_config_pontos_parcela_em_dia CHECK ((pontos_parcela_em_dia >= 0));
alter table public.clube_config add constraint clube_config_id_check CHECK ((id = 1));
alter table public.clube_config add constraint clube_config_pontos_primeira_parcela_check CHECK ((pontos_primeira_parcela >= 0));
alter table public.clube_recompensas add constraint clube_recompensas_pontos_check CHECK ((pontos > 0));
alter table public.clube_resgates add constraint clube_resgates_status_check CHECK ((status = ANY (ARRAY['solicitado'::text, 'aprovado'::text, 'separacao'::text, 'entregue'::text, 'cancelado'::text])));
alter table public.comissao_eventos add constraint comissao_eventos_status_check CHECK ((status = ANY (ARRAY['prevista'::text, 'validada'::text, 'paga'::text, 'cancelada'::text])));
alter table public.comissao_eventos add constraint comissao_eventos_valor_comissao_check CHECK ((valor_comissao >= (0)::numeric));
alter table public.comissao_regras add constraint comissao_regras_tipo_check CHECK ((tipo = ANY (ARRAY['valor_fixo'::text, 'percentual'::text, 'faixa'::text])));
alter table public.comissao_regras add constraint comissao_regras_valor_check CHECK ((valor >= (0)::numeric));
alter table public.comissoes add constraint comissoes_evento_check CHECK ((evento = ANY (ARRAY['primeira_parcela_confirmada'::text, 'comparecimento'::text, 'manual_configuracao_financeiro'::text])));
alter table public.comissoes add constraint comissoes_status_check CHECK ((status = ANY (ARRAY['pendente'::text, 'aprovada'::text, 'paga'::text])));
alter table public.comissoes add constraint comissoes_valor_check CHECK ((valor >= (0)::numeric));
alter table public.conciliacao_pagamentos add constraint conciliacao_pagamentos_banco_chk CHECK ((length(TRIM(BOTH FROM banco)) > 0));
alter table public.conciliacao_pagamentos add constraint conciliacao_pagamentos_divergencia_chk CHECK (((status <> 'divergencia'::status_conciliacao_pagamento) OR (length(TRIM(BOTH FROM COALESCE(motivo_divergencia, ''::text))) > 0)));
alter table public.conciliacao_pagamentos add constraint conciliacao_pagamentos_ignorado_chk CHECK (((status <> 'ignorado'::status_conciliacao_pagamento) OR (length(TRIM(BOTH FROM COALESCE(observacao, motivo_divergencia, ''::text))) > 0)));
alter table public.conciliacao_pagamentos add constraint conciliacao_pagamentos_valor_chk CHECK ((valor_recebido >= (0)::numeric));
alter table public.configuracoes add constraint chk_configuracoes_cirurgia_intervalo_minimo_dias CHECK (((cirurgia_intervalo_minimo_dias >= 0) AND (cirurgia_intervalo_minimo_dias <= 365)));
alter table public.configuracoes add constraint configuracoes_desconto_pix_percentual_check CHECK (((desconto_pix_percentual >= (0)::numeric) AND (desconto_pix_percentual <= (100)::numeric)));
alter table public.configuracoes add constraint singleton CHECK ((id = 1));
alter table public.conta_azul_vinculos add constraint conta_azul_vinculos_baixa_origem_check CHECK ((baixa_origem = ANY (ARRAY['sra'::text, 'conta_azul'::text])));
alter table public.conta_azul_vinculos add constraint conta_azul_vinculos_estado_check CHECK ((estado = ANY (ARRAY['aguardando_criacao'::text, 'enviando'::text, 'aguardando_protocolo'::text, 'vinculado'::text, 'conflito'::text, 'erro_criacao'::text, 'desvinculado'::text])));
alter table public.crm_vendas_entrada add constraint crm_vendas_entrada_status_check CHECK ((status = ANY (ARRAY['aguardando_conferencia'::text, 'convertido'::text, 'ignorado'::text, 'erro'::text])));
alter table public.datas_liberacao_financeira add constraint datas_liberacao_financeira_vagas_check CHECK ((vagas_totais >= 0));
alter table public.feedback_jornada add constraint feedback_jornada_nota_check CHECK (((nota >= 1) AND (nota <= 5)));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_desconto_check CHECK ((desconto >= (0)::numeric));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_forma_check CHECK (((forma_pagamento IS NULL) OR (forma_pagamento = ANY (ARRAY['pix'::text, 'dinheiro'::text, 'transferencia'::text, 'boleto'::text, 'cartao'::text, 'cheque'::text, 'comprovante'::text, 'outro'::text]))));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_juros_check CHECK ((juros >= (0)::numeric));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_multa_check CHECK ((multa >= (0)::numeric));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_origem_check CHECK ((origem = ANY (ARRAY['manual'::text, 'comprovante'::text, 'historico'::text, 'banco'::text, 'mercado_pago'::text, 'conta_azul'::text])));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_rejeicao_check CHECK (((status_validacao <> 'rejeitado'::text) OR (NULLIF(btrim(motivo_rejeicao), ''::text) IS NOT NULL)));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_status_validacao_check CHECK ((status_validacao = ANY (ARRAY['pendente'::text, 'validado'::text, 'rejeitado'::text])));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_total_check CHECK ((desconto <= ((valor_original + juros) + multa)));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_validado_check CHECK (((status_validacao <> 'validado'::text) OR ((data_pagamento IS NOT NULL) AND ((forma_pagamento IS NOT NULL) OR (origem = 'historico'::text)) AND (round(valor_recebido, 2) = round((((valor_original + juros) + multa) - desconto), 2)) AND (validado_por IS NOT NULL) AND (validado_em IS NOT NULL))));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_valor_original_check CHECK ((valor_original >= (0)::numeric));
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_valor_recebido_check CHECK ((valor_recebido >= (0)::numeric));
alter table public.frases_do_dia add constraint frases_do_dia_origem_check CHECK ((origem = ANY (ARRAY['ia'::text, 'catalogo'::text])));
alter table public.frases_do_dia add constraint frases_do_dia_segmento_check CHECK ((segmento = ANY (ARRAY['inicio'::text, 'construindo'::text, 'metade'::text, 'quitado'::text])));
alter table public.frases_do_dia add constraint frases_do_dia_tema_check CHECK (((char_length(tema) >= 2) AND (char_length(tema) <= 60)));
alter table public.frases_do_dia add constraint frases_do_dia_texto_check CHECK (((char_length(texto) >= 10) AND (char_length(texto) <= 220)));
alter table public.home_campanhas_config add constraint home_campanhas_config_id_check CHECK ((id ~ '^[a-z0-9-]{3,60}$'::text));
alter table public.home_campanhas_config add constraint home_campanhas_config_ordem_check CHECK (((ordem IS NULL) OR ((ordem >= '-1000'::integer) AND (ordem <= 1000))));
alter table public.importacoes_boletos add constraint importacoes_boletos_nivel_confianca_chk CHECK (((nivel_confianca IS NULL) OR (nivel_confianca = ANY (ARRAY['alta'::text, 'media'::text, 'baixa'::text]))));
alter table public.importacoes_boletos add constraint importacoes_boletos_status_vinculacao_chk CHECK ((status_vinculacao = ANY (ARRAY['pendente'::text, 'analisado'::text, 'aguardando_confirmacao'::text, 'vinculado'::text, 'ignorado'::text, 'revisar'::text])));
alter table public.indicacoes_clientes add constraint chk_indicacao_nao_propria CHECK (((indicado_cliente_id IS NULL) OR (indicado_cliente_id <> indicador_cliente_id)));
alter table public.indicacoes_clientes add constraint indicacoes_clientes_consentimento_check CHECK (((consentimento_contato = true) AND (consentimento_registrado_em IS NOT NULL)));
alter table public.indicacoes_clientes add constraint indicacoes_clientes_status_check CHECK ((status = ANY (ARRAY['enviada'::text, 'qualificada'::text, 'venda'::text, 'invalidada'::text])));
alter table public.integracao_conflitos add constraint integracao_conflitos_estado_check CHECK ((estado = ANY (ARRAY['aberto'::text, 'resolvido'::text, 'descartado'::text])));
alter table public.integracao_eventos add constraint integracao_eventos_status_check CHECK ((status = ANY (ARRAY['recebido'::text, 'processado'::text, 'parcial'::text, 'ignorado'::text, 'erro'::text])));
alter table public.integracao_fila add constraint integracao_fila_estado_check CHECK ((estado = ANY (ARRAY['pendente'::text, 'processando'::text, 'concluida'::text, 'erro'::text, 'cancelada'::text])));
alter table public.integracao_importacao_itens add constraint integracao_importacao_itens_resultado_check CHECK ((resultado = ANY (ARRAY['criada'::text, 'atualizada'::text, 'duplicada'::text, 'cliente_existente'::text, 'ignorada'::text, 'erro'::text, 'importada_apos_revisao'::text])));
alter table public.integracao_importacoes add constraint integracao_importacoes_origem_check CHECK ((origem = ANY (ARRAY['manual'::text, 'agendada'::text, 'webhook'::text])));
alter table public.integracao_importacoes add constraint integracao_importacoes_status_check CHECK ((status = ANY (ARRAY['em_andamento'::text, 'concluida'::text, 'parcial'::text, 'erro'::text])));
alter table public.integracoes_config add constraint integracoes_config_funcao_check CHECK ((funcao ~ '^[a-z0-9_]{2,40}$'::text));
alter table public.integracoes_config add constraint integracoes_config_provedor_check CHECK ((provedor ~ '^[a-z0-9_]{2,40}$'::text));
alter table public.integracoes_estado add constraint integracoes_estado_provedor_check CHECK ((provedor ~ '^[a-z_]{2,40}$'::text));
alter table public.mensagens_do_dia add constraint mensagens_do_dia_erro_check CHECK (((erro IS NULL) OR (char_length(erro) <= 500)));
alter table public.mensagens_do_dia add constraint mensagens_do_dia_origem_check CHECK (((origem IS NULL) OR (origem = ANY (ARRAY['ia'::text, 'catalogo'::text, 'ultima_valida'::text, 'admin'::text]))));
alter table public.mensagens_do_dia add constraint mensagens_do_dia_publicavel_tem_texto CHECK (((status = ANY (ARRAY['gerando'::text, 'falha_geracao'::text])) OR ((texto IS NOT NULL) AND (tema IS NOT NULL) AND (origem IS NOT NULL))));
alter table public.mensagens_do_dia add constraint mensagens_do_dia_status_check CHECK ((status = ANY (ARRAY['gerando'::text, 'aguardando_aprovacao'::text, 'pronta'::text, 'falha_geracao'::text])));
alter table public.mensagens_do_dia add constraint mensagens_do_dia_tema_check CHECK (((tema IS NULL) OR ((char_length(tema) >= 2) AND (char_length(tema) <= 60))));
alter table public.mensagens_do_dia add constraint mensagens_do_dia_texto_check CHECK (((texto IS NULL) OR ((char_length(texto) >= 10) AND (char_length(texto) <= 220))));
alter table public.metas_colaboradores add constraint metas_colaboradores_mes_check CHECK (((mes >= 1) AND (mes <= 12)));
alter table public.monitoramento_acessos add constraint monitoramento_acessos_actor_type_check CHECK ((actor_type = ANY (ARRAY['cliente'::text, 'admin'::text])));
alter table public.monitoramento_erros add constraint monitoramento_erros_actor_type_check CHECK (((actor_type IS NULL) OR (actor_type = ANY (ARRAY['cliente'::text, 'admin'::text, 'staff'::text, 'system'::text, 'anonymous'::text]))));
alter table public.monitoramento_erros add constraint monitoramento_erros_duration_ms_check CHECK (((duration_ms IS NULL) OR (duration_ms >= 0)));
alter table public.monitoramento_erros add constraint monitoramento_erros_nivel_check CHECK ((nivel = ANY (ARRAY['info'::text, 'warn'::text, 'error'::text, 'fatal'::text])));
alter table public.monitoramento_erros add constraint monitoramento_erros_origem_check CHECK ((origem = ANY (ARRAY['frontend'::text, 'api'::text, 'diagnostico'::text])));
alter table public.notificacao_eventos add constraint notificacao_eventos_categoria_check CHECK ((categoria = ANY (ARRAY['pagamentos'::text, 'agenda'::text, 'jornada'::text, 'clube'::text])));
alter table public.notificacao_lote_itens add constraint notificacao_lote_itens_mensagem_check CHECK (((mensagem IS NULL) OR (char_length(mensagem) <= 400)));
alter table public.notificacao_lote_itens add constraint notificacao_lote_itens_status_check CHECK ((status = ANY (ARRAY['PREPARED'::text, 'AWAITING_APPROVAL'::text, 'QUEUED'::text, 'PROCESSING'::text, 'PROVIDER_ACCEPTED'::text, 'IN_APP_ONLY'::text, 'FAILED'::text, 'SKIPPED_DEDUPLICATION'::text, 'SKIPPED_RULE'::text, 'OPENED'::text, 'CLICKED'::text, 'CANCELLED'::text])));
alter table public.notificacao_lote_itens add constraint notificacao_lote_itens_titulo_check CHECK (((titulo IS NULL) OR (char_length(titulo) <= 80)));
alter table public.notificacao_lotes add constraint notificacao_lotes_instrucao_check CHECK (((instrucao IS NULL) OR (char_length(instrucao) <= 300)));
alter table public.notificacao_lotes add constraint notificacao_lotes_origem_check CHECK ((origem = ANY (ARRAY['manual'::text, 'rotina'::text])));
alter table public.notificacao_lotes add constraint notificacao_lotes_status_check CHECK ((status = ANY (ARRAY['PREPARED'::text, 'AI_GENERATION_FAILED'::text, 'AWAITING_APPROVAL'::text, 'QUEUED_FOR_ALLOWED_WINDOW'::text, 'PROCESSING'::text, 'COMPLETED'::text, 'CANCELLED'::text])));
alter table public.notificacao_lotes add constraint notificacao_lotes_tipo_check CHECK ((tipo = 'financeiro'::text));
alter table public.novas_vendas add constraint novas_vendas_quantidade_parcelas_chk CHECK (((quantidade_parcelas IS NULL) OR (quantidade_parcelas > 0)));
alter table public.novas_vendas add constraint novas_vendas_valor_contrato_chk CHECK ((valor_contrato >= (0)::numeric));
alter table public.pagamentos_externos add constraint pagamentos_externos_status_validacao_check CHECK ((status_validacao = ANY (ARRAY['aguardando_validacao'::text, 'em_analise'::text, 'aprovado'::text, 'rejeitado'::text, 'conciliado'::text])));
alter table public.regras_operacionais add constraint regras_operacionais_id_check CHECK ((id = 1));
alter table public.regras_operacionais add constraint regras_operacionais_percentual_12_24x_check CHECK (((percentual_12_24x > (0)::numeric) AND (percentual_12_24x <= (100)::numeric)));
alter table public.regras_operacionais add constraint regras_operacionais_percentual_36x_check CHECK (((percentual_36x > (0)::numeric) AND (percentual_36x <= (100)::numeric)));
alter table public.regras_operacionais add constraint regras_operacionais_percentual_48_72x_check CHECK (((percentual_48_72x > (0)::numeric) AND (percentual_48_72x <= (100)::numeric)));
alter table public.regras_operacionais add constraint regras_operacionais_prazo_liberacao_dias_uteis_check CHECK (((prazo_liberacao_dias_uteis >= 1) AND (prazo_liberacao_dias_uteis <= 30)));
alter table public.regras_operacionais add constraint regras_operacionais_teto_mensal_operacional_check CHECK (((teto_mensal_operacional > (0)::numeric) AND (teto_mensal_operacional <= (100000000)::numeric)));
alter table public.relatorios_exportacoes add constraint relatorios_exportacoes_formato_check CHECK ((formato = ANY (ARRAY['pdf'::text, 'xlsx'::text])));
alter table public.solicitacoes_liberacao_financeira add constraint solicitacoes_liberacao_financeira_saldo_restante_check CHECK ((saldo_restante >= (0)::numeric));
alter table public.solicitacoes_liberacao_financeira add constraint solicitacoes_liberacao_financeira_taxa_cartao_check CHECK ((taxa_cartao >= (0)::numeric));
alter table public.solicitacoes_liberacao_financeira add constraint solicitacoes_liberacao_financeira_total_com_taxa_check CHECK ((total_com_taxa >= (0)::numeric));
alter table public.solicitacoes_remarcacao_agendamento add constraint solicitacoes_remarcacao_agendamento_status_check CHECK ((status = ANY (ARRAY['pendente'::text, 'aprovada'::text, 'recusada'::text])));
alter table public.solicitacoes_remarcacao_agendamento add constraint solicitacoes_remarcacao_agendamento_tipo_check CHECK ((tipo = ANY (ARRAY['termos'::text, 'cirurgia'::text])));
alter table public.treinamento_progresso add constraint treinamento_progresso_progresso_check CHECK (((progresso >= 0) AND (progresso <= 100)));
alter table public.treinamentos add constraint treinamentos_tipo_check CHECK ((tipo = ANY (ARRAY['video'::text, 'imagem'::text, 'texto'::text, 'misto'::text])));
alter table public.agendamentos add constraint agendamentos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.agendamentos add constraint agendamentos_comparecimento_registrado_por_fkey FOREIGN KEY (comparecimento_registrado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.agendamentos add constraint agendamentos_data_id_fkey FOREIGN KEY (data_id) REFERENCES datas(id) ON DELETE CASCADE;
alter table public.agendamentos add constraint agendamentos_sdr_id_fkey FOREIGN KEY (sdr_id) REFERENCES colaboradores(id) ON DELETE SET NULL;
alter table public.boletos add constraint boletos_carne_id_fkey FOREIGN KEY (carne_id) REFERENCES carnes(id) ON DELETE SET NULL;
alter table public.boletos add constraint boletos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.carne_importacoes add constraint carne_importacoes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.carnes add constraint carnes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT;
alter table public.cliente_app_devices add constraint cliente_app_devices_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.cliente_pontos add constraint cliente_pontos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.cliente_pontos_eventos add constraint cliente_pontos_eventos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.clientes add constraint clientes_vendedora_id_fkey FOREIGN KEY (vendedora_id) REFERENCES colaboradores(id) ON DELETE SET NULL;
alter table public.clube_beneficios_cliente add constraint clube_beneficios_cliente_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.clube_resgates add constraint clube_resgates_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.clube_resgates add constraint clube_resgates_recompensa_id_fkey FOREIGN KEY (recompensa_id) REFERENCES clube_recompensas(id) ON DELETE RESTRICT;
alter table public.colaboradores add constraint colaboradores_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.comissao_eventos add constraint comissao_eventos_colaborador_id_fkey FOREIGN KEY (colaborador_id) REFERENCES colaboradores(id) ON DELETE CASCADE;
alter table public.comissao_eventos add constraint comissao_eventos_regra_id_fkey FOREIGN KEY (regra_id) REFERENCES comissao_regras(id) ON DELETE SET NULL;
alter table public.comissoes add constraint comissoes_agendamento_id_fkey FOREIGN KEY (agendamento_id) REFERENCES agendamentos(id) ON DELETE SET NULL;
alter table public.comissoes add constraint comissoes_boleto_id_fkey FOREIGN KEY (boleto_id) REFERENCES boletos(id) ON DELETE SET NULL;
alter table public.comissoes add constraint comissoes_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.comissoes add constraint comissoes_colaborador_id_fkey FOREIGN KEY (colaborador_id) REFERENCES colaboradores(id) ON DELETE RESTRICT;
alter table public.comissoes add constraint comissoes_gerado_por_fkey FOREIGN KEY (gerado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.conciliacao_pagamentos add constraint conciliacao_pagamentos_boleto_id_fkey FOREIGN KEY (boleto_id) REFERENCES boletos(id) ON DELETE SET NULL;
alter table public.conciliacao_pagamentos add constraint conciliacao_pagamentos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.conciliacao_pagamentos_historico add constraint conciliacao_pagamentos_historico_boleto_id_fkey FOREIGN KEY (boleto_id) REFERENCES boletos(id) ON DELETE SET NULL;
alter table public.conciliacao_pagamentos_historico add constraint conciliacao_pagamentos_historico_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.conciliacao_pagamentos_historico add constraint conciliacao_pagamentos_historico_conciliacao_pagamento_id_fkey FOREIGN KEY (conciliacao_pagamento_id) REFERENCES conciliacao_pagamentos(id) ON DELETE CASCADE;
alter table public.conta_azul_vinculos add constraint conta_azul_vinculos_boleto_id_fkey FOREIGN KEY (boleto_id) REFERENCES boletos(id) ON DELETE RESTRICT;
alter table public.conta_azul_vinculos add constraint conta_azul_vinculos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT;
alter table public.feedback_jornada add constraint feedback_jornada_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_boleto_id_fkey FOREIGN KEY (boleto_id) REFERENCES boletos(id) ON DELETE RESTRICT;
alter table public.financeiro_recebimentos add constraint financeiro_recebimentos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT;
alter table public.importacoes_boletos add constraint importacoes_boletos_boleto_id_fkey FOREIGN KEY (boleto_id) REFERENCES boletos(id) ON DELETE SET NULL;
alter table public.importacoes_boletos add constraint importacoes_boletos_boleto_sugerido_id_fkey FOREIGN KEY (boleto_sugerido_id) REFERENCES boletos(id) ON DELETE SET NULL;
alter table public.importacoes_boletos add constraint importacoes_boletos_boleto_vinculado_id_fkey FOREIGN KEY (boleto_vinculado_id) REFERENCES boletos(id) ON DELETE SET NULL;
alter table public.importacoes_boletos add constraint importacoes_boletos_carne_id_fkey FOREIGN KEY (carne_id) REFERENCES carnes(id) ON DELETE SET NULL;
alter table public.importacoes_boletos add constraint importacoes_boletos_carne_sugerido_id_fkey FOREIGN KEY (carne_sugerido_id) REFERENCES carnes(id) ON DELETE SET NULL;
alter table public.importacoes_boletos add constraint importacoes_boletos_carne_vinculado_id_fkey FOREIGN KEY (carne_vinculado_id) REFERENCES carnes(id) ON DELETE SET NULL;
alter table public.importacoes_boletos add constraint importacoes_boletos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.importacoes_boletos add constraint importacoes_boletos_cliente_sugerido_id_fkey FOREIGN KEY (cliente_sugerido_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.importacoes_boletos add constraint importacoes_boletos_cliente_vinculado_id_fkey FOREIGN KEY (cliente_vinculado_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.indicacoes_clientes add constraint indicacoes_clientes_indicado_cliente_id_fkey FOREIGN KEY (indicado_cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.indicacoes_clientes add constraint indicacoes_clientes_indicador_cliente_id_fkey FOREIGN KEY (indicador_cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.integracao_conflitos add constraint integracao_conflitos_vinculo_id_fkey FOREIGN KEY (vinculo_id) REFERENCES conta_azul_vinculos(id) ON DELETE SET NULL;
alter table public.integracao_importacao_itens add constraint integracao_importacao_itens_importacao_id_fkey FOREIGN KEY (importacao_id) REFERENCES integracao_importacoes(id) ON DELETE CASCADE;
alter table public.integracao_importacao_itens add constraint integracao_importacao_itens_nova_venda_id_fkey FOREIGN KEY (nova_venda_id) REFERENCES novas_vendas(id) ON DELETE SET NULL;
alter table public.mensagens_motivacionais add constraint mensagens_motivacionais_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.metas_colaboradores add constraint metas_colaboradores_colaborador_id_fkey FOREIGN KEY (colaborador_id) REFERENCES colaboradores(id) ON DELETE CASCADE;
alter table public.notificacao_agendadas add constraint notificacao_agendadas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.notificacao_logs add constraint notificacao_logs_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.notificacao_logs add constraint notificacao_logs_notificacao_id_fkey FOREIGN KEY (notificacao_id) REFERENCES notificacoes_cliente(id);
alter table public.notificacao_lote_itens add constraint notificacao_lote_itens_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.notificacao_lote_itens add constraint notificacao_lote_itens_lote_id_fkey FOREIGN KEY (lote_id) REFERENCES notificacao_lotes(id) ON DELETE CASCADE;
alter table public.notificacoes_cliente add constraint notificacoes_cliente_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.notificacoes_colaboradores add constraint notificacoes_colaboradores_colaborador_id_fkey FOREIGN KEY (colaborador_id) REFERENCES colaboradores(id) ON DELETE CASCADE;
alter table public.novas_vendas add constraint novas_vendas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.novas_vendas add constraint novas_vendas_importacao_id_fkey FOREIGN KEY (importacao_id) REFERENCES integracao_importacoes(id) ON DELETE SET NULL;
alter table public.novas_vendas add constraint novas_vendas_vendedora_id_fkey FOREIGN KEY (vendedora_id) REFERENCES colaboradores(id) ON DELETE SET NULL;
alter table public.pagamentos_externos add constraint pagamentos_externos_boleto_id_fkey FOREIGN KEY (boleto_id) REFERENCES boletos(id) ON DELETE SET NULL;
alter table public.pagamentos_externos add constraint pagamentos_externos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.push_tokens add constraint push_tokens_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.solicitacoes_liberacao_financeira add constraint solicitacoes_liberacao_financeira_agendamento_id_fkey FOREIGN KEY (agendamento_id) REFERENCES agendamentos(id) ON DELETE SET NULL;
alter table public.solicitacoes_liberacao_financeira add constraint solicitacoes_liberacao_financeira_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.solicitacoes_remarcacao_agendamento add constraint solicitacoes_remarcacao_agendamento_agendamento_id_fkey FOREIGN KEY (agendamento_id) REFERENCES agendamentos(id) ON DELETE CASCADE;
alter table public.solicitacoes_remarcacao_agendamento add constraint solicitacoes_remarcacao_agendamento_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.solicitacoes_remarcacao_agendamento add constraint solicitacoes_remarcacao_agendamento_data_id_fkey FOREIGN KEY (data_id) REFERENCES datas(id) ON DELETE SET NULL;
alter table public.treinamento_progresso add constraint treinamento_progresso_colaborador_id_fkey FOREIGN KEY (colaborador_id) REFERENCES colaboradores(id) ON DELETE CASCADE;
alter table public.treinamento_progresso add constraint treinamento_progresso_treinamento_id_fkey FOREIGN KEY (treinamento_id) REFERENCES treinamentos(id) ON DELETE CASCADE;
alter table public.web_push_subscriptions add constraint web_push_subscriptions_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
