CREATE INDEX idx_agendamentos_cliente ON public.agendamentos USING btree (cliente_id);
CREATE INDEX idx_agendamentos_comparecimento ON public.agendamentos USING btree (comparecimento_status);
CREATE INDEX idx_agendamentos_data ON public.agendamentos USING btree (data_id);
CREATE INDEX idx_agendamentos_data_cirurgia ON public.agendamentos USING btree (data_cirurgia);
CREATE INDEX idx_agendamentos_data_cirurgia_horario ON public.agendamentos USING btree (data_cirurgia, horario_cirurgia) WHERE ((data_cirurgia IS NOT NULL) AND (status <> 'cancelado'::status_agendamento));
CREATE INDEX idx_agendamentos_horario_termos ON public.agendamentos USING btree (horario_termos) WHERE (status = 'confirmado'::status_agendamento);
CREATE INDEX idx_agendamentos_liberacao_pendente_v46 ON public.agendamentos USING btree (id) WHERE ((status = 'confirmado'::status_agendamento) AND (comparecimento_status = 'compareceu'::text) AND (quitacao_status = 'paga'::text) AND (agenda_cirurgica_liberada_em IS NULL));
CREATE INDEX idx_agendamentos_previsao_cirurgia ON public.agendamentos USING btree (previsao_cirurgia) WHERE (previsao_cirurgia_confirmada_em IS NOT NULL);
CREATE INDEX idx_agendamentos_previsao_liberacao ON public.agendamentos USING btree (previsao_liberacao_financeira);
CREATE INDEX idx_agendamentos_processo_concluido ON public.agendamentos USING btree (processo_concluido_em);
CREATE INDEX idx_agendamentos_release_queue ON public.agendamentos USING btree (cliente_id, status, data_cirurgia, previsao_cirurgia_confirmada_em);
CREATE INDEX idx_agendamentos_sdr ON public.agendamentos USING btree (sdr_id);
CREATE INDEX idx_agendamentos_status ON public.agendamentos USING btree (status);
CREATE INDEX idx_agendamentos_status_data ON public.agendamentos USING btree (status, data_id);
CREATE INDEX idx_agendamentos_status_previsao ON public.agendamentos USING btree (status, previsao_liberacao_financeira);
CREATE UNIQUE INDEX uniq_agendamento_confirmado_por_cliente ON public.agendamentos USING btree (cliente_id) WHERE (status = 'confirmado'::status_agendamento);
CREATE INDEX boletos_comprovante_pendente_data_idx ON public.boletos USING btree (comprovante_enviado_em DESC) WHERE ((status = 'pendente_confirmacao'::status_boleto) AND (comprovante_url IS NOT NULL));
CREATE INDEX idx_boletos_carne ON public.boletos USING btree (carne_id);
CREATE INDEX idx_boletos_cliente ON public.boletos USING btree (cliente_id);
CREATE INDEX idx_boletos_cliente_parcela ON public.boletos USING btree (cliente_id, numero_parcela);
CREATE INDEX idx_boletos_cliente_status ON public.boletos USING btree (cliente_id, status);
CREATE INDEX idx_boletos_instituicao_identificador ON public.boletos USING btree (lower(TRIM(BOTH FROM instituicao_financeira)), lower(TRIM(BOTH FROM identificador_externo))) WHERE ((identificador_externo IS NOT NULL) AND (length(TRIM(BOTH FROM identificador_externo)) > 0));
CREATE INDEX idx_boletos_status ON public.boletos USING btree (status);
CREATE INDEX idx_boletos_status_vencimento ON public.boletos USING btree (status, data_vencimento);
CREATE INDEX idx_boletos_suspensa ON public.boletos USING btree (cliente_id, suspensa) WHERE (suspensa = true);
CREATE UNIQUE INDEX uniq_boleto_por_parcela ON public.boletos USING btree (cliente_id, numero_parcela);
CREATE INDEX idx_carne_importacoes_cliente_sha ON public.carne_importacoes USING btree (cliente_id, arquivo_sha256);
CREATE INDEX idx_carnes_cliente ON public.carnes USING btree (cliente_id);
CREATE INDEX idx_carnes_data_geracao ON public.carnes USING btree (data_geracao DESC);
CREATE INDEX idx_carnes_instituicao ON public.carnes USING btree (lower(TRIM(BOTH FROM instituicao_financeira)));
CREATE INDEX idx_carnes_status ON public.carnes USING btree (status);
CREATE UNIQUE INDEX uniq_carne_instituicao_identificador ON public.carnes USING btree (lower(TRIM(BOTH FROM instituicao_financeira)), lower(TRIM(BOTH FROM identificador_externo)));
CREATE INDEX idx_cliente_app_devices_cliente ON public.cliente_app_devices USING btree (cliente_id);
CREATE INDEX idx_cliente_app_devices_last_access ON public.cliente_app_devices USING btree (last_access_at DESC);
CREATE INDEX idx_cliente_app_devices_push ON public.cliente_app_devices USING btree (push_active);
CREATE INDEX idx_cliente_app_devices_pwa ON public.cliente_app_devices USING btree (is_pwa_installed);
CREATE INDEX idx_cliente_pontos_eventos_cliente_created ON public.cliente_pontos_eventos USING btree (cliente_id, created_at DESC);
CREATE INDEX idx_clientes_ativos_recent ON public.clientes USING btree (created_at DESC, id DESC) WHERE (ativo = true);
CREATE INDEX idx_clientes_cpf ON public.clientes USING btree (cpf);
CREATE INDEX idx_clientes_custeio_confirmado ON public.clientes USING btree (custeio_confirmado_em);
CREATE INDEX idx_clientes_financeiro_confirmado ON public.clientes USING btree (financeiro_confirmado_em);
CREATE INDEX idx_clientes_liberacao_financeira_solicitada ON public.clientes USING btree (liberacao_financeira_solicitada_em);
CREATE INDEX idx_clientes_revisao_data ON public.clientes USING btree (status_revisao_financeira, data_atingiu_percentual);
CREATE INDEX idx_clientes_status_cirurgia ON public.clientes USING btree (status_cirurgia);
CREATE INDEX idx_clientes_status_contrato ON public.clientes USING btree (status_contrato);
CREATE INDEX idx_clientes_status_financeiro ON public.clientes USING btree (status_financeiro);
CREATE INDEX idx_clientes_vendedora ON public.clientes USING btree (vendedora_id);
CREATE UNIQUE INDEX uq_clientes_cpf_nao_arquivada ON public.clientes USING btree (cpf) WHERE (arquivado_em IS NULL);
CREATE INDEX idx_clube_beneficios_cliente_cliente_id ON public.clube_beneficios_cliente USING btree (cliente_id);
CREATE INDEX idx_clube_campanhas_catalogo ON public.clube_campanhas USING btree (ativo, ordem, created_at) WHERE (excluido_em IS NULL);
CREATE INDEX idx_clube_recompensas_catalogo_visivel ON public.clube_recompensas USING btree (ativo, ordem, pontos) WHERE (excluido_em IS NULL);
CREATE INDEX idx_clube_resgates_cliente_created ON public.clube_resgates USING btree (cliente_id, created_at DESC);
CREATE UNIQUE INDEX idx_clube_resgates_idempotency_key ON public.clube_resgates USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE UNIQUE INDEX colaboradores_auth_user_unique ON public.colaboradores USING btree (auth_user_id) WHERE (auth_user_id IS NOT NULL);
CREATE INDEX idx_colaboradores_cargo_ativo ON public.colaboradores USING btree (cargo, ativo);
CREATE UNIQUE INDEX comissao_evento_referencia_unique ON public.comissao_eventos USING btree (colaborador_id, regra_id, referencia_tipo, referencia_id) WHERE (referencia_id IS NOT NULL);
CREATE INDEX comissao_eventos_colaborador_idx ON public.comissao_eventos USING btree (colaborador_id, competencia DESC, created_at DESC);
CREATE INDEX comissao_regras_cargo_ativo_idx ON public.comissao_regras USING btree (cargo, ativo, vigencia_inicio DESC);
CREATE INDEX idx_comissoes_cliente_evento ON public.comissoes USING btree (cliente_id, evento);
CREATE INDEX idx_comissoes_colaborador_created ON public.comissoes USING btree (colaborador_id, created_at DESC);
CREATE INDEX idx_conciliacao_banco ON public.conciliacao_pagamentos USING btree (lower(TRIM(BOTH FROM banco)));
CREATE INDEX idx_conciliacao_boleto ON public.conciliacao_pagamentos USING btree (boleto_id);
CREATE INDEX idx_conciliacao_cliente ON public.conciliacao_pagamentos USING btree (cliente_id);
CREATE INDEX idx_conciliacao_data_pagamento ON public.conciliacao_pagamentos USING btree (data_pagamento DESC);
CREATE INDEX idx_conciliacao_status ON public.conciliacao_pagamentos USING btree (status);
CREATE UNIQUE INDEX uniq_conciliacao_banco_identificador ON public.conciliacao_pagamentos USING btree (lower(TRIM(BOTH FROM banco)), identificador_externo) WHERE ((identificador_externo IS NOT NULL) AND (length(TRIM(BOTH FROM identificador_externo)) > 0));
CREATE INDEX idx_conciliacao_historico_created_at ON public.conciliacao_pagamentos_historico USING btree (created_at DESC);
CREATE INDEX idx_conciliacao_historico_pagamento ON public.conciliacao_pagamentos_historico USING btree (conciliacao_pagamento_id, created_at DESC);
CREATE INDEX conta_azul_vinculos_estado_idx ON public.conta_azul_vinculos USING btree (estado);
CREATE INDEX conta_azul_vinculos_evento_idx ON public.conta_azul_vinculos USING btree (ca_evento_id);
CREATE INDEX conta_azul_vinculos_verificacao_idx ON public.conta_azul_vinculos USING btree (ultima_sincronizacao_em NULLS FIRST);
CREATE INDEX crm_vendas_deal_idx ON public.crm_vendas_entrada USING btree (provedor, external_deal_id, created_at DESC);
CREATE INDEX crm_vendas_status_idx ON public.crm_vendas_entrada USING btree (status, created_at DESC);
CREATE UNIQUE INDEX crm_vendas_transaction_unique ON public.crm_vendas_entrada USING btree (provedor, transaction_uuid) WHERE ((transaction_uuid IS NOT NULL) AND (length(TRIM(BOTH FROM transaction_uuid)) > 0));
CREATE INDEX idx_datas_data ON public.datas USING btree (data);
CREATE INDEX idx_datas_status ON public.datas USING btree (status);
CREATE INDEX idx_datas_liberacao_financeira_data ON public.datas_liberacao_financeira USING btree (data);
CREATE INDEX idx_datas_liberacao_financeira_status ON public.datas_liberacao_financeira USING btree (status);
CREATE INDEX idx_feedback_jornada_cliente ON public.feedback_jornada USING btree (cliente_id);
CREATE INDEX idx_feedback_jornada_created_at ON public.feedback_jornada USING btree (created_at DESC);
CREATE INDEX idx_financeiro_recebimentos_boleto ON public.financeiro_recebimentos USING btree (boleto_id);
CREATE INDEX idx_financeiro_recebimentos_cliente ON public.financeiro_recebimentos USING btree (cliente_id);
CREATE INDEX idx_financeiro_recebimentos_data ON public.financeiro_recebimentos USING btree (data_pagamento DESC);
CREATE INDEX idx_financeiro_recebimentos_validacao ON public.financeiro_recebimentos USING btree (status_validacao, created_at DESC);
CREATE UNIQUE INDEX uniq_financeiro_recebimento_validado_boleto ON public.financeiro_recebimentos USING btree (boleto_id) WHERE (status_validacao = 'validado'::text);
CREATE INDEX frases_do_dia_created_at_idx ON public.frases_do_dia USING btree (created_at DESC);
CREATE INDEX idx_importacoes_boletos_boleto ON public.importacoes_boletos USING btree (boleto_id);
CREATE INDEX idx_importacoes_boletos_boleto_sugerido ON public.importacoes_boletos USING btree (boleto_sugerido_id);
CREATE INDEX idx_importacoes_boletos_carne ON public.importacoes_boletos USING btree (carne_id);
CREATE INDEX idx_importacoes_boletos_cliente ON public.importacoes_boletos USING btree (cliente_id);
CREATE INDEX idx_importacoes_boletos_cliente_sugerido ON public.importacoes_boletos USING btree (cliente_sugerido_id);
CREATE INDEX idx_importacoes_boletos_created_at ON public.importacoes_boletos USING btree (created_at DESC);
CREATE INDEX idx_importacoes_boletos_instituicao ON public.importacoes_boletos USING btree (lower(TRIM(BOTH FROM instituicao_financeira)));
CREATE INDEX idx_importacoes_boletos_nivel_confianca ON public.importacoes_boletos USING btree (nivel_confianca);
CREATE INDEX idx_importacoes_boletos_status ON public.importacoes_boletos USING btree (status);
CREATE INDEX idx_importacoes_boletos_vinculacao_status ON public.importacoes_boletos USING btree (status_vinculacao);
CREATE UNIQUE INDEX uniq_importacao_boleto_arquivo_sha256 ON public.importacoes_boletos USING btree (arquivo_sha256) WHERE ((arquivo_sha256 IS NOT NULL) AND (length(TRIM(BOTH FROM arquivo_sha256)) > 0));
CREATE UNIQUE INDEX uniq_importacao_boleto_instituicao_externo ON public.importacoes_boletos USING btree (lower(TRIM(BOTH FROM instituicao_financeira)), lower(TRIM(BOTH FROM identificador_externo))) WHERE ((instituicao_financeira IS NOT NULL) AND (identificador_externo IS NOT NULL) AND (length(TRIM(BOTH FROM instituicao_financeira)) > 0) AND (length(TRIM(BOTH FROM identificador_externo)) > 0));
CREATE UNIQUE INDEX uniq_importacao_boleto_instituicao_nosso ON public.importacoes_boletos USING btree (lower(TRIM(BOTH FROM instituicao_financeira)), lower(TRIM(BOTH FROM nosso_numero))) WHERE ((instituicao_financeira IS NOT NULL) AND (nosso_numero IS NOT NULL) AND (length(TRIM(BOTH FROM instituicao_financeira)) > 0) AND (length(TRIM(BOTH FROM nosso_numero)) > 0));
CREATE INDEX idx_indicacoes_clientes_indicador_created ON public.indicacoes_clientes USING btree (indicador_cliente_id, created_at DESC);
CREATE INDEX idx_indicacoes_clientes_status_created ON public.indicacoes_clientes USING btree (status, created_at DESC);
CREATE UNIQUE INDEX uq_indicacoes_indicado_venda ON public.indicacoes_clientes USING btree (indicado_cliente_id) WHERE ((status = 'venda'::text) AND (indicado_cliente_id IS NOT NULL));
CREATE UNIQUE INDEX integracao_conflitos_aberto_uniq ON public.integracao_conflitos USING btree (provedor, referencia, tipo) WHERE (estado = 'aberto'::text);
CREATE INDEX integracao_conflitos_estado_idx ON public.integracao_conflitos USING btree (provedor, estado, created_at DESC);
CREATE INDEX integracao_eventos_provider_created_idx ON public.integracao_eventos USING btree (provedor, created_at DESC);
CREATE UNIQUE INDEX integracao_eventos_provider_event_unique ON public.integracao_eventos USING btree (provedor, event_id) WHERE ((event_id IS NOT NULL) AND (length(TRIM(BOTH FROM event_id)) > 0));
CREATE INDEX integracao_eventos_status_idx ON public.integracao_eventos USING btree (status, created_at DESC);
CREATE INDEX integracao_fila_pendentes_idx ON public.integracao_fila USING btree (provedor, estado, proxima_tentativa_em);
CREATE INDEX integracao_importacao_itens_imp_idx ON public.integracao_importacao_itens USING btree (importacao_id);
CREATE INDEX integracao_importacao_itens_revisao_idx ON public.integracao_importacao_itens USING btree (resultado, created_at DESC) WHERE (resultado = ANY (ARRAY['duplicada'::text, 'cliente_existente'::text]));
CREATE INDEX integracao_importacoes_provedor_idx ON public.integracao_importacoes USING btree (provedor, iniciado_em DESC);
CREATE INDEX integracoes_credenciais_provedor_idx ON public.integracoes_credenciais USING btree (provedor);
CREATE INDEX idx_logs_alteracoes_detalhes_cliente_id ON public.logs_alteracoes USING btree (((detalhes ->> 'cliente_id'::text)));
CREATE INDEX idx_logs_alteracoes_entidade_id ON public.logs_alteracoes USING btree (entidade_id);
CREATE INDEX idx_logs_created_at ON public.logs_alteracoes USING btree (created_at DESC);
CREATE INDEX idx_monitoramento_acessos_ator ON public.monitoramento_acessos USING btree (actor_type, actor_id, criado_em DESC);
CREATE INDEX idx_monitoramento_acessos_criado_em ON public.monitoramento_acessos USING btree (criado_em DESC);
CREATE INDEX monitoramento_erros_action_idx ON public.monitoramento_erros USING btree (action, criado_em DESC) WHERE (action IS NOT NULL);
CREATE INDEX monitoramento_erros_actor_idx ON public.monitoramento_erros USING btree (actor_type, actor_id, criado_em DESC) WHERE (actor_id IS NOT NULL);
CREATE INDEX monitoramento_erros_criado_em_idx ON public.monitoramento_erros USING btree (criado_em DESC);
CREATE INDEX monitoramento_erros_nivel_idx ON public.monitoramento_erros USING btree (nivel, criado_em DESC);
CREATE INDEX monitoramento_erros_request_id_idx ON public.monitoramento_erros USING btree (request_id, criado_em DESC) WHERE (request_id IS NOT NULL);
CREATE INDEX monitoramento_erros_rota_idx ON public.monitoramento_erros USING btree (rota, criado_em DESC);
CREATE INDEX idx_notificacao_agendadas_cliente_id ON public.notificacao_agendadas USING btree (cliente_id);
CREATE INDEX idx_notificacao_agendadas_created_at ON public.notificacao_agendadas USING btree (created_at);
CREATE INDEX idx_notificacao_agendadas_referencia ON public.notificacao_agendadas USING btree (referencia_id);
CREATE INDEX idx_notificacao_agendadas_status ON public.notificacao_agendadas USING btree (status);
CREATE INDEX idx_notificacao_logs_cliente_created ON public.notificacao_logs USING btree (cliente_id, created_at DESC);
CREATE INDEX idx_notificacao_logs_cliente_id ON public.notificacao_logs USING btree (cliente_id);
CREATE INDEX idx_notificacao_logs_cliente_tipo_created ON public.notificacao_logs USING btree (cliente_id, tipo, created_at DESC);
CREATE INDEX idx_notificacao_logs_created ON public.notificacao_logs USING btree (created_at DESC);
CREATE INDEX idx_notificacao_logs_push_pendente ON public.notificacao_logs USING btree (created_at) WHERE (push_status = 'pendente'::text);
CREATE INDEX idx_notificacao_logs_referencia_created ON public.notificacao_logs USING btree (referencia_id, created_at DESC);
CREATE INDEX notificacao_lote_itens_cliente_idx ON public.notificacao_lote_itens USING btree (cliente_id, created_at DESC);
CREATE INDEX notificacao_lote_itens_lote_idx ON public.notificacao_lote_itens USING btree (lote_id);
CREATE INDEX notificacao_lotes_created_idx ON public.notificacao_lotes USING btree (created_at DESC);
CREATE INDEX notificacao_lotes_status_idx ON public.notificacao_lotes USING btree (status);
CREATE UNIQUE INDEX ux_notificacao_templates_regua ON public.notificacao_templates USING btree (tipo, dias_referencia) WHERE (tipo = ANY (ARRAY['parcela_vencer'::text, 'parcela_atrasada'::text]));
CREATE INDEX idx_notificacoes_cliente_cliente_id ON public.notificacoes_cliente USING btree (cliente_id);
CREATE INDEX idx_notificacoes_cliente_created ON public.notificacoes_cliente USING btree (cliente_id, created_at DESC);
CREATE INDEX idx_notificacoes_cliente_created_at ON public.notificacoes_cliente USING btree (created_at DESC);
CREATE INDEX idx_notificacoes_cliente_lida ON public.notificacoes_cliente USING btree (cliente_id, lida);
CREATE UNIQUE INDEX ux_notificacoes_cliente_evento_dedupe ON public.notificacoes_cliente USING btree (cliente_id, evento, chave_dedupe) WHERE (chave_dedupe IS NOT NULL);
CREATE INDEX idx_notificacoes_colaborador_created ON public.notificacoes_colaboradores USING btree (colaborador_id, created_at DESC);
CREATE UNIQUE INDEX uniq_resumo_colaborador_dia ON public.notificacoes_colaboradores USING btree (colaborador_id, tipo, data_referencia) WHERE (data_referencia IS NOT NULL);
CREATE INDEX idx_novas_vendas_cliente ON public.novas_vendas USING btree (cliente_id);
CREATE INDEX idx_novas_vendas_cpf ON public.novas_vendas USING btree (cpf);
CREATE INDEX idx_novas_vendas_data_venda ON public.novas_vendas USING btree (data_venda DESC);
CREATE INDEX idx_novas_vendas_status ON public.novas_vendas USING btree (status);
CREATE INDEX idx_novas_vendas_vendedora ON public.novas_vendas USING btree (vendedora_id);
CREATE INDEX novas_vendas_rd_campaign_idx ON public.novas_vendas USING btree (rd_campaign_id);
CREATE INDEX novas_vendas_rd_owner_idx ON public.novas_vendas USING btree (rd_owner_id);
CREATE INDEX novas_vendas_rd_status_idx ON public.novas_vendas USING btree (rd_status);
CREATE INDEX novas_vendas_rd_sync_idx ON public.novas_vendas USING btree (sincronizado_rd_em DESC);
CREATE INDEX pagamentos_externos_boleto_idx ON public.pagamentos_externos USING btree (boleto_id);
CREATE INDEX pagamentos_externos_cliente_idx ON public.pagamentos_externos USING btree (cliente_id);
CREATE INDEX pagamentos_externos_validacao_idx ON public.pagamentos_externos USING btree (status_validacao, created_at DESC);
CREATE INDEX idx_push_tokens_cliente_id ON public.push_tokens USING btree (cliente_id);
CREATE INDEX idx_relatorios_exportacoes_created_at ON public.relatorios_exportacoes USING btree (created_at DESC);
CREATE INDEX idx_relatorios_exportacoes_modulo ON public.relatorios_exportacoes USING btree (modulo);
CREATE INDEX idx_solicitacoes_liberacao_agendamento ON public.solicitacoes_liberacao_financeira USING btree (agendamento_id);
CREATE INDEX idx_solicitacoes_liberacao_cliente ON public.solicitacoes_liberacao_financeira USING btree (cliente_id, created_at DESC);
CREATE UNIQUE INDEX uq_solicitacao_liberacao_pendente ON public.solicitacoes_liberacao_financeira USING btree (cliente_id) WHERE (status = ANY (ARRAY['pendente'::status_solicitacao_liberacao, 'em_analise'::status_solicitacao_liberacao]));
CREATE INDEX idx_solicitacoes_remarcacao_cliente ON public.solicitacoes_remarcacao_agendamento USING btree (cliente_id, status, created_at DESC);
CREATE INDEX idx_solicitacoes_remarcacao_pendentes ON public.solicitacoes_remarcacao_agendamento USING btree (status, created_at);
CREATE INDEX idx_web_push_subscriptions_cliente ON public.web_push_subscriptions USING btree (cliente_id);
CREATE INDEX idx_web_push_subscriptions_device ON public.web_push_subscriptions USING btree (cliente_id, device_key) WHERE (device_key IS NOT NULL);
CREATE INDEX idx_web_push_subscriptions_updated ON public.web_push_subscriptions USING btree (updated_at DESC);
