CREATE TRIGGER trg_agenda_sync_agendamentos AFTER INSERT OR DELETE OR UPDATE ON public.agendamentos FOR EACH STATEMENT EXECUTE FUNCTION bump_agenda_sync_state();
CREATE TRIGGER trg_agendamentos_updated_at BEFORE UPDATE ON public.agendamentos FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notificar_agendamento AFTER INSERT OR UPDATE ON public.agendamentos FOR EACH ROW EXECUTE FUNCTION notificar_agendamento();
CREATE TRIGGER trg_clube_notificar_boleto_status AFTER UPDATE OF status ON public.boletos FOR EACH ROW WHEN ((old.status IS DISTINCT FROM new.status)) EXECUTE FUNCTION clube_notificar_boleto_status();
CREATE TRIGGER trg_sincronizar_revisao_financeira AFTER INSERT OR DELETE OR UPDATE ON public.boletos FOR EACH ROW EXECUTE FUNCTION sincronizar_revisao_financeira();
CREATE TRIGGER trg_carnes_updated_at BEFORE UPDATE ON public.carnes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_clientes_updated_at BEFORE UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notificar_revisao_financeira AFTER UPDATE OF status_revisao_financeira ON public.clientes FOR EACH ROW EXECUTE FUNCTION notificar_revisao_financeira();
CREATE TRIGGER trg_novas_vendas_avancar AFTER UPDATE OF acesso_app_liberado ON public.clientes FOR EACH ROW EXECUTE FUNCTION novas_vendas_avancar_concluidas();
CREATE TRIGGER trg_proteger_exclusao_cliente_financeiro BEFORE DELETE ON public.clientes FOR EACH ROW EXECUTE FUNCTION proteger_exclusao_cliente_com_historico_financeiro();
CREATE TRIGGER trg_colaboradores_updated_at BEFORE UPDATE ON public.colaboradores FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_comissoes_updated_at BEFORE UPDATE ON public.comissoes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_conciliacao_pagamentos_updated_at BEFORE UPDATE ON public.conciliacao_pagamentos FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_configuracoes_updated_at BEFORE UPDATE ON public.configuracoes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_agenda_sync_datas AFTER INSERT OR DELETE OR UPDATE ON public.datas FOR EACH STATEMENT EXECUTE FUNCTION bump_agenda_sync_state();
CREATE TRIGGER trg_datas_updated_at BEFORE UPDATE ON public.datas FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_agenda_sync_datas_cirurgia AFTER INSERT OR DELETE OR UPDATE ON public.datas_liberacao_financeira FOR EACH STATEMENT EXECUTE FUNCTION bump_agenda_sync_state();
CREATE TRIGGER trg_datas_liberacao_financeira_updated_at BEFORE UPDATE ON public.datas_liberacao_financeira FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_financeiro_recebimentos_updated_at BEFORE UPDATE ON public.financeiro_recebimentos FOR EACH ROW EXECUTE FUNCTION financeiro_set_updated_at();
CREATE TRIGGER trg_importacoes_boletos_updated_at BEFORE UPDATE ON public.importacoes_boletos FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_lgpd_proteger_log_alteracao BEFORE INSERT OR UPDATE ON public.logs_alteracoes FOR EACH ROW EXECUTE FUNCTION lgpd_proteger_log_alteracao();
CREATE TRIGGER trg_mensagens_motivacionais_updated_at BEFORE UPDATE ON public.mensagens_motivacionais FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_metas_colaboradores_updated_at BEFORE UPDATE ON public.metas_colaboradores FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notificacao_agendadas_updated_at BEFORE UPDATE ON public.notificacao_agendadas FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notificacao_templates_updated_at BEFORE UPDATE ON public.notificacao_templates FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_novas_vendas_updated_at BEFORE UPDATE ON public.novas_vendas FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notificar_liberacao_financeira AFTER UPDATE OF status ON public.solicitacoes_liberacao_financeira FOR EACH ROW EXECUTE FUNCTION notificar_liberacao_financeira();
CREATE TRIGGER trg_solicitacao_liberacao_updated_at BEFORE UPDATE ON public.solicitacoes_liberacao_financeira FOR EACH ROW EXECUTE FUNCTION atualizar_solicitacao_liberacao_updated_at();
