import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { toast } from "sonner";
import {
  buscarClube, indicarAmiga, resgatarPremio, usarBeneficio, VOUCHER_CONSULTA_KEY,
  type ClubeData, type ClubeRecompensa,
} from "@/lib/clube";

interface ClubeScreenProps { onVoltar?: () => void; onIrParcelas: () => void; }

function CoinIcon() { return <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.55" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="8"/><path d="M9 10.2c.6-.8 1.5-1.2 2.7-1.2 1.5 0 2.6.7 2.6 1.8 0 2.8-5.3 1.1-5.3 4 0 1.1 1.1 1.9 2.8 1.9 1.2 0 2.2-.4 2.9-1.3M12 7.2v1.5M12 16.8v1.5"/></svg>; }
function GiftIcon({ size=19 }: { size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"><path d="M20 12v9H4v-9"/><path d="M2 7h20v5H2z"/><path d="M12 21V7"/><path d="M12 7H7.5a2.3 2.3 0 1 1 2-3.5L12 7Z"/><path d="M12 7h4.5a2.3 2.3 0 1 0-2-3.5L12 7Z"/></svg>; }
function TicketIcon() { return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"><path d="M3 8a2 2 0 0 0 2-2h14a2 2 0 0 0 2 2v2a2 2 0 0 0 0 4v2a2 2 0 0 0-2 2H5a2 2 0 0 0-2-2v-2a2 2 0 0 0 0-4V8Z"/><path d="M12 7v10"/></svg>; }

function BottomSheet({ aberto, onFechar, titulo, children }: { aberto: boolean; onFechar: () => void; titulo: string; children: React.ReactNode }) {
  return <AnimatePresence>{aberto && <div className="sl-sheet-backdrop" onClick={onFechar}><motion.div onClick={(e)=>e.stopPropagation()} initial={{ y: "100%" }} animate={{ y: 0 }} exit={{ y: "100%" }} transition={{ duration:.16 }} className="sl-sheet"><div className="sl-sheet-grab"/><div className="flex items-center justify-between"><h3 className="m-0 font-heading text-[22px] font-semibold text-[#392927]">{titulo}</h3><button type="button" onClick={onFechar} className="flex h-8 w-8 items-center justify-center rounded-full text-[#9A8A86]"><svg width="15" height="15" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.3"><path d="M3 3l10 10M13 3 3 13"/></svg></button></div><div className="pt-3">{children}</div></motion.div></div>}</AnimatePresence>;
}

function PremioCard({ recompensa, saldo, onResgatar }: { recompensa: ClubeRecompensa; saldo: number; onResgatar:(r:ClubeRecompensa)=>void }) {
  const elegivel = saldo >= recompensa.pontos && (recompensa.estoque === null || recompensa.estoque > 0);
  return <div className="flex items-center gap-[11px] rounded-[17px] border border-[#ECE2DF] bg-white p-[13px] shadow-[0_4px_14px_rgba(73,42,47,.025)]">
    <div className="flex h-10 w-10 flex-none items-center justify-center rounded-[13px] border border-[#E9D9D5] bg-[#FFF9F8] text-[#B86575]"><GiftIcon/></div>
    <div className="min-w-0 flex-1"><div className="text-[12.4px] font-semibold text-[#4B3936]">{recompensa.titulo}</div><div className="pt-[2px] text-[9.7px] font-light leading-[1.4] text-[#9A8A86]">{recompensa.descricao ?? "Benefício exclusivo Sra. Luck."}</div></div>
    <div className="flex-none text-right"><div className="flex items-center justify-end gap-1 text-[9.8px] font-bold text-[#8A671E]"><span className="inline-flex h-[15px] w-[15px] items-center justify-center rounded-full border border-[#E8D39E] bg-[#FBF4E7]"><CoinIcon/></span>{recompensa.pontos}</div><button type="button" disabled={!elegivel} onClick={()=>onResgatar(recompensa)} className="mt-[5px] rounded-[9px] px-[8px] py-[6px] text-[8.7px] font-semibold" style={elegivel?{background:"#6B1F2E",color:"#FFF"}:{background:"#F4EFED",color:"#A89A96"}}>{elegivel?"Resgatar":`Faltam ${Math.max(0,recompensa.pontos-saldo)}`}</button></div>
  </div>;
}

export function ClubeScreen({ onVoltar, onIrParcelas }: ClubeScreenProps) {
  const [dados,setDados]=useState<ClubeData|null>(null); const [carregando,setCarregando]=useState(true); const [sheet,setSheet]=useState<"carteira"|"indicacoes"|"como"|null>(null); const [indicarAberto,setIndicarAberto]=useState(false); const [resgateAlvo,setResgateAlvo]=useState<ClubeRecompensa|null>(null); const [busy,setBusy]=useState(false);
  async function carregar(){try{setDados(await buscarClube())}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível abrir o Clube de Vantagens.")}finally{setCarregando(false)}}
  useEffect(()=>{void carregar()},[]);
  const voucher=dados?.beneficios.find((x)=>x.beneficio_key===VOUCHER_CONSULTA_KEY)??null;
  async function confirmarResgate(){if(!resgateAlvo)return;setBusy(true);try{await resgatarPremio(resgateAlvo.id,crypto.randomUUID());toast.success("Resgate solicitado! A equipe vai confirmar em breve.");setResgateAlvo(null);await carregar()}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível concluir o resgate.")}finally{setBusy(false)}}
  async function usarVoucher(){if(!voucher)return;setBusy(true);try{await usarBeneficio(voucher.id);toast.success("Voucher marcado como utilizado. Combine o horário com a equipe.");await carregar()}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível usar o voucher.")}finally{setBusy(false)}}

  return <div className="sl-tab pb-6">
    <div className="px-[18px] pt-[calc(max(env(safe-area-inset-top),0px)+11px)]">
      <div className="flex items-center justify-between gap-3 pr-[86px]">
        {onVoltar ? <button type="button" onClick={onVoltar} className="flex min-w-0 items-center gap-[7px] text-[12px] font-normal text-[#6B1F2E]"><svg width="15" height="15" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.35"><path d="M9 3 5 7l4 4"/></svg>Mais</button> : <img src="/brand/sra-luck-logo.png" alt="Sra. Luck" className="w-[91px] object-contain" />}
        <div className="flex items-center gap-[7px]">
          <button type="button" onClick={()=>setSheet("carteira")} className="flex h-[34px] items-center gap-[6px] rounded-full border border-[#E8D9D5] bg-white pl-2 pr-[10px] text-[#6B1F2E] shadow-[0_3px_12px_rgba(67,38,42,.04)]"><span className="flex h-[22px] w-[22px] items-center justify-center rounded-full border border-[#E8D39E] bg-[#FBF4E7] text-[#9B741E]"><CoinIcon/></span><span className="font-heading text-[16px] font-semibold leading-none">{dados?.saldo??0}</span></button>
          <button type="button" onClick={()=>setSheet("indicacoes")} className="relative flex h-[34px] w-[34px] items-center justify-center rounded-full border border-[#E8D9D5] bg-white text-[#B86575] shadow-[0_3px_12px_rgba(67,38,42,.04)]"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M19 8v6M22 11h-6"/></svg>{Boolean(dados?.indicacoes.emAnalise)&&<span className="absolute -right-0.5 -top-[3px] flex h-[15px] min-w-[15px] items-center justify-center rounded-full border-2 border-[#FBF7F5] bg-[#6B1F2E] px-[3px] text-[7.5px] font-bold text-white">{dados?.indicacoes.emAnalise}</span>}</button>
          <button type="button" onClick={()=>setSheet("como")} className="flex h-[34px] w-[34px] items-center justify-center rounded-full border border-[#E8D9D5] bg-white text-[#B86575] shadow-[0_3px_12px_rgba(67,38,42,.04)]"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4"><circle cx="12" cy="12" r="9"/><path d="M12 10.2v5M12 7.2h.01"/></svg></button>
        </div>
      </div>
      <div className="pt-[14px]"><div className="text-[8.4px] font-semibold uppercase tracking-[.16em] text-[#B86575]">Benefícios Sra. Luck</div><div className="pt-[2px] font-heading text-[23px] font-semibold leading-[1.08] text-[#392927]">Clube de vantagens</div><div className="max-w-[330px] pt-1 text-[10.5px] font-light leading-[1.42] text-[#8D7D79]">Indique, acumule pontos e escolha benefícios pensados para acompanhar sua jornada.</div></div>
    </div>

    {carregando ? <div className="px-[18px] py-12 text-center text-[10.5px] font-light text-[#9A8A86]">Carregando...</div> : <>
      {!voucher && <div className="mx-[18px] mt-[17px] rounded-[18px] bg-gradient-to-br from-[#6B1F2E] to-[#7C2B3B] p-[14px] text-white shadow-[0_10px_26px_rgba(107,31,46,.13)]"><div className="flex items-start gap-[11px]"><div className="flex h-[39px] w-[39px] flex-none items-center justify-center rounded-[13px] border border-white/15 bg-white/10 text-[#F2D7B0]"><GiftIcon/></div><div className="min-w-0 flex-1"><div className="text-[8.5px] font-semibold uppercase tracking-[.13em] text-[#E9CFA8]">Missão de boas-vindas</div><div className="pt-[2px] font-heading text-[19px] font-semibold">Pague sua primeira parcela</div><div className="pt-1 text-[10px] font-light leading-[1.45] text-white/70">Ao confirmar o primeiro pagamento, você recebe <strong className="font-semibold text-white">+50 moedas</strong> e libera seu <strong className="font-semibold text-white">Voucher de Consulta com o Doutor</strong>.</div></div></div><button type="button" onClick={onIrParcelas} className="mt-3 w-full rounded-[11px] bg-white px-3 py-[10px] text-[10.5px] font-semibold text-[#6B1F2E]">Ver primeira parcela</button></div>}

      <div className="px-[18px] pt-[21px]">
        <div className="flex items-end justify-between gap-[10px] pb-[10px]"><div><div className="font-heading text-[21px] font-semibold text-[#43322F]">Prêmios disponíveis</div><div className="pt-[2px] text-[10.3px] font-light text-[#978783]">Escolha uma conquista para aproveitar.</div></div><button type="button" onClick={()=>setSheet("carteira")} className="text-[9px] font-semibold text-[#B86575]">Ver moedas</button></div>

        <div className="rounded-[20px] border border-[#E6D5D0] bg-gradient-to-br from-white to-[#FFF7F5] p-[15px] shadow-[0_8px_24px_rgba(73,42,47,.045)]">
          <div className="flex items-start gap-3"><div className="flex h-[46px] w-[46px] flex-none items-center justify-center rounded-[15px] border border-[#E7D1CD] bg-[#F9EFED] text-[#B86575]"><TicketIcon/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-[7px]"><div><div className="text-[8.5px] font-semibold uppercase tracking-[.12em] text-[#B86575]">Prêmio de boas-vindas</div><div className="pt-[2px] font-heading text-[20px] font-semibold leading-[1.1] text-[#43322F]">Voucher de consulta com o Doutor</div></div><span className="whitespace-nowrap rounded-full px-[7px] py-1 text-[7.8px] font-bold uppercase" style={voucher?.status==="disponivel"?{background:"#EEF7F0",color:"#3F7D5B"}:{background:"#F5F1EF",color:"#988985"}}>{voucher?.status==="disponivel"?"Disponível":"Bloqueado"}</span></div><div className="pt-[5px] text-[10px] font-light leading-[1.45] text-[#8D7D79]">1 consulta com o Doutor, liberada após a confirmação da sua 1ª parcela. O voucher não consome moedas e o agendamento é combinado com a equipe Sra. Luck.</div></div></div>
          <div className="mt-3 flex items-center justify-between gap-[10px] border-t border-[#F0E4E1] pt-[11px]"><div className="flex items-center gap-[6px] text-[9px] text-[#8D7D79]"><span className="flex h-[21px] w-[21px] items-center justify-center rounded-full border border-[#E8D39E] bg-[#FBF4E7] text-[#9B741E]"><CoinIcon/></span><strong className="font-semibold text-[#5E4A46]">+50</strong> na missão</div>{voucher?.status==="disponivel"&&<button type="button" disabled={busy} onClick={()=>void usarVoucher()} className="rounded-[10px] bg-[#6B1F2E] px-[10px] py-2 text-[9.5px] font-semibold text-white">Usar voucher</button>}</div>
        </div>

        <div className="mt-[10px] grid gap-[9px]">{(dados?.recompensas??[]).map((r)=><PremioCard key={r.id} recompensa={r} saldo={dados?.saldo??0} onResgatar={setResgateAlvo}/>)}{(dados?.recompensas??[]).length===0&&<div className="rounded-[17px] border border-[#ECE2DF] bg-white p-5 text-center text-[10.5px] font-light text-[#9A8A86]">Nenhum prêmio cadastrado no momento.</div>}</div>
      </div>

      <button type="button" onClick={()=>setSheet("como")} className="mx-[18px] mt-[18px] flex w-[calc(100%-36px)] items-center justify-between gap-[10px] rounded-[15px] border border-[#EEE4E1] bg-[#FBF7F5] px-[13px] py-3 text-left"><span><span className="block text-[10.8px] font-medium text-[#5A4541]">Quer entender o Clube?</span><span className="block pt-[2px] text-[9.5px] font-light text-[#978783]">Veja como ganhar moedas e usar seus benefícios.</span></span><span className="text-[9px] font-semibold text-[#B86575]">Como funciona ›</span></button>
    </>}

    <BottomSheet aberto={sheet==="carteira"} onFechar={()=>setSheet(null)} titulo="Suas moedas"><div className="flex items-center gap-[9px]"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-[#E8D39E] bg-[#FBF4E7] text-[#9B741E]"><CoinIcon/></span><div><div className="font-heading text-[29px] font-semibold leading-none text-[#6B1F2E]">{dados?.saldo??0}</div><div className="pt-1 text-[9px] font-light text-[#9A8A86]">moedas disponíveis</div></div></div><div className="pt-4 text-[8.5px] font-semibold uppercase tracking-[.13em] text-[#A9837C]">Histórico de moedas</div><div className="mt-2 grid gap-2">{(dados?.historico??[]).map((e)=><div key={e.id} className="flex items-center justify-between rounded-[13px] border border-[#EEE4E1] bg-[#FCFAF9] px-3 py-[10px]"><div><div className="text-[10.8px] font-medium text-[#4B3936]">{e.tipo==="indicacao"?"Indicação confirmada":e.tipo==="bonus"?"Bônus":e.tipo==="resgate"?"Resgate":"Ajuste"}</div><div className="pt-[2px] text-[9px] font-light text-[#A2938F]">{new Date(e.created_at).toLocaleDateString("pt-BR")}</div></div><div className="font-heading text-[16px] font-semibold" style={{color:e.pontos>=0?"#3F7D5B":"#B86575"}}>{e.pontos>=0?"+":""}{e.pontos}</div></div>)}</div></BottomSheet>

    <BottomSheet aberto={sheet==="indicacoes"} onFechar={()=>setSheet(null)} titulo="Suas indicações"><p className="m-0 text-[10.5px] font-light leading-[1.5] text-[#8D7D79]">As moedas entram quando a indicação é confirmada pela equipe.</p><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-[13px] border border-[#DCE9DF] bg-[#F6FAF7] p-3 text-center"><div className="font-heading text-[25px] font-semibold text-[#3F7D5B]">{dados?.indicacoes.confirmadas??0}</div><div className="text-[8.5px] uppercase tracking-[.08em] text-[#8A7B77]">Confirmadas</div></div><div className="rounded-[13px] border border-[#EADBB8] bg-[#FFF9EE] p-3 text-center"><div className="font-heading text-[25px] font-semibold text-[#9B741E]">{dados?.indicacoes.emAnalise??0}</div><div className="text-[8.5px] uppercase tracking-[.08em] text-[#8A7B77]">Em análise</div></div></div><button type="button" onClick={()=>setIndicarAberto(true)} className="mt-4 w-full rounded-[11px] bg-[#6B1F2E] px-3 py-[11px] text-[10.5px] font-semibold text-white">Indicar uma amiga</button></BottomSheet>

    <BottomSheet aberto={sheet==="como"} onFechar={()=>setSheet(null)} titulo="Como funciona"><div className="grid gap-3">{[["01","Você indica","Compartilhe o nome e telefone de uma amiga com a equipe Sra. Luck."],["02","A equipe confirma","Quando a indicação atingir o critério real, a equipe confirma o status."],["03","Você escolhe","Troque suas moedas por benefícios disponíveis no catálogo."]].map(([n,t,d])=><div key={n} className="flex items-start gap-3"><span className="flex h-7 w-7 flex-none items-center justify-center rounded-full bg-[#F7EFED] text-[9px] font-semibold text-[#7D2434]">{n}</span><div><div className="text-[11.5px] font-medium text-[#4B3936]">{t}</div><div className="pt-[2px] text-[9.8px] font-light leading-[1.48] text-[#8D7D79]">{d}</div></div></div>)}</div></BottomSheet>

    <IndicarModal aberto={indicarAberto} onFechar={()=>setIndicarAberto(false)} onEnviado={()=>{setIndicarAberto(false);void carregar()}}/>
    {resgateAlvo&&<div className="fixed inset-0 z-[90] flex items-end justify-center bg-black/50"><div className="w-full max-w-[430px] rounded-t-[24px] bg-white p-[18px] pb-[calc(max(env(safe-area-inset-bottom),0px)+18px)]"><div className="sl-sheet-grab"/><div className="font-heading text-[22px] font-semibold text-[#392927]">Confirmar resgate</div><div className="pt-1 text-[10.8px] font-light text-[#8D7D79]">{resgateAlvo.titulo}</div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><div className="text-[8.5px] text-[#A2938F]">Saldo atual</div><div className="font-heading text-[18px] font-semibold text-[#6B1F2E]">{dados?.saldo??0}</div></div><div><div className="text-[8.5px] text-[#A2938F]">Resgate</div><div className="font-heading text-[18px] font-semibold text-[#B86575]">-{resgateAlvo.pontos}</div></div><div><div className="text-[8.5px] text-[#A2938F]">Depois</div><div className="font-heading text-[18px] font-semibold text-[#6B1F2E]">{Math.max(0,(dados?.saldo??0)-resgateAlvo.pontos)}</div></div></div><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setResgateAlvo(null)} className="rounded-[11px] border border-[#E7DAD6] px-3 py-[11px] text-[10.5px] font-semibold text-[#6B1F2E]">Agora não</button><button type="button" disabled={busy} onClick={()=>void confirmarResgate()} className="rounded-[11px] bg-[#6B1F2E] px-3 py-[11px] text-[10.5px] font-semibold text-white">{busy?"Aguarde...":"Solicitar resgate"}</button></div></div></div>}
  </div>;
}

function IndicarModal({ aberto,onFechar,onEnviado }:{aberto:boolean;onFechar:()=>void;onEnviado:()=>void}){const[nome,setNome]=useState("");const[telefone,setTelefone]=useState("");const[busy,setBusy]=useState(false);useEffect(()=>{if(aberto){setNome("");setTelefone("")}},[aberto]);if(!aberto)return null;async function enviar(){if(!nome.trim())return;setBusy(true);try{await indicarAmiga(nome.trim(),telefone.trim());toast.success("Indicação enviada! A equipe vai acompanhar.");onEnviado()}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível enviar a indicação.")}finally{setBusy(false)}}return <div className="fixed inset-0 z-[95] flex items-end justify-center bg-black/50"><div className="w-full max-w-[430px] rounded-t-[24px] bg-white p-[18px] pb-[calc(max(env(safe-area-inset-bottom),0px)+18px)]"><div className="sl-sheet-grab"/><div className="font-heading text-[22px] font-semibold text-[#392927]">Indicar uma amiga</div><div className="pt-1 text-[10.5px] font-light text-[#8D7D79]">Compartilhe os dados dela para nossa equipe entrar em contato.</div><label className="mt-4 block text-[9px] font-medium uppercase tracking-[.1em] text-[#9A8C88]">Nome<input value={nome} onChange={e=>setNome(e.target.value)} className="mt-[7px] w-full rounded-[14px] border border-[#E6DAD6] bg-white px-4 py-[13px] text-[14px] text-[#2E2422] outline-none focus:border-[#6B1F2E]"/></label><label className="mt-3 block text-[9px] font-medium uppercase tracking-[.1em] text-[#9A8C88]">Telefone<input value={telefone} onChange={e=>setTelefone(e.target.value)} className="mt-[7px] w-full rounded-[14px] border border-[#E6DAD6] bg-white px-4 py-[13px] text-[14px] text-[#2E2422] outline-none focus:border-[#6B1F2E]"/></label><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={onFechar} className="rounded-[11px] border border-[#E7DAD6] px-3 py-[11px] text-[10.5px] font-semibold text-[#6B1F2E]">Cancelar</button><button type="button" disabled={!nome.trim()||busy} onClick={()=>void enviar()} className="rounded-[11px] bg-[#6B1F2E] px-3 py-[11px] text-[10.5px] font-semibold text-white disabled:opacity-50">{busy?"Enviando...":"Enviar"}</button></div></div></div>}
