// J01 — acesso público, login da cliente, parcelas e envio de comprovante (QA-01 Ana)
import { abrir, BASE } from "./lib.mjs";
import { writeFileSync } from "node:fs";
const { page, shot, fim, rede } = await abrir("J01-cliente-login-parcelas", { mobile: true });
const r = {};
await page.goto(`${BASE}/`); await page.waitForLoadState("networkidle"); r.raiz = page.url(); await shot("publico-raiz-redireciona-login");
await page.getByPlaceholder("000.000.000-00").fill("90000000175");
await page.getByPlaceholder("DD/MM/AAAA").fill("15/01/1990");
await page.getByRole("button", { name: "Acessar minha área" }).click();
await page.waitForLoadState("networkidle"); await page.waitForTimeout(1500);
r.aposLogin = page.url();
const agoraNao = page.getByRole("button", { name: "Agora não" });
if (await agoraNao.isVisible().catch(() => false)) await agoraNao.click();
await shot("home");
await page.getByRole("button", { name: "Financeiro" }).last().click();
await page.waitForLoadState("networkidle"); await page.waitForTimeout(800);
await shot("financeiro");
writeFileSync(`${process.env.SP_TXT || "/tmp"}/j01-fin.txt`, await page.locator("body").innerText());
await page.getByRole("button", { name: "Pagar" }).first().click();
await page.waitForTimeout(800); await shot("pagar-parcela-4");
writeFileSync(`${process.env.SP_TXT || "/tmp"}/j01-pagar.txt`, await page.locator("body").innerText());
await page.getByRole("button", { name: /PIX/ }).click();
await page.waitForTimeout(700); await shot("pix");
writeFileSync(`${process.env.SP_TXT || "/tmp"}/j01-pix.txt`, await page.locator("body").innerText());
const voltarPix = page.getByRole("button", { name: /Voltar|Fechar/ }).last();
await page.keyboard.press("Escape").catch(() => {});
await page.getByRole("button", { name: "Pagar" }).first().click().catch(() => {});
await page.waitForTimeout(500);
await page.getByRole("button", { name: /Já paguei/ }).click();
await page.waitForTimeout(700); await shot("enviar-comprovante");
writeFileSync(`${process.env.SP_TXT || "/tmp"}/j01-comp.txt`, await page.locator("body").innerText());
r.inputsArquivo = await page.locator('input[type="file"]').count();
await page.locator('input[type="file"]').setInputFiles("/home/user/qa-supabase/qa/fixtures/comprovante-qa.pdf");
await page.waitForTimeout(500); await shot("comprovante-selecionado");
const envio = page.waitForResponse((res) => res.url().includes("/api/cliente/boletos/") && res.request().method() === "POST", { timeout: 20000 });
await page.getByRole("button", { name: "Enviar para análise" }).click();
const resEnvio = await envio; r.envio = { status: resEnvio.status(), path: new URL(resEnvio.url()).pathname, body: await resEnvio.text() };
await page.waitForTimeout(1500); await shot("apos-envio");
writeFileSync(`${process.env.SP_TXT || "/tmp"}/j01-apos.txt`, await page.locator("body").innerText());
await page.reload({ waitUntil: "domcontentloaded" }); await page.waitForTimeout(2500); await page.waitForTimeout(1200);
const agoraNao2 = page.getByRole("button", { name: "Agora não" });
if (await agoraNao2.isVisible().catch(() => false)) await agoraNao2.click();
await page.getByRole("button", { name: "Financeiro" }).last().click({ timeout: 5000 }).catch(() => {}); await page.waitForTimeout(1000);
await shot("apos-reload-financeiro");
writeFileSync(`${process.env.SP_TXT || "/tmp"}/j01-reload.txt`, await page.locator("body").innerText());
r.botoes = await page.locator("button, a").evaluateAll(els => els.map(e => (e.innerText || e.getAttribute("aria-label") || "").trim().replace(/\s+/g, " ")).filter(Boolean));
await fim(r);
console.log(JSON.stringify(r, null, 1));
console.log(rede.map(x => `${x.method} ${x.path} ${x.status}`).join("\n"));
