import { useMemo, useState } from "react";
import { BadgeDollarSign, BookOpenCheck, CheckCircle2, ChevronRight, Home, Medal, PlayCircle, Target, UserRound } from "lucide-react";
import { trainings } from "../credit-ops/sample-data";
import "../../styles/staff-pwa.css";

type Role="Vendedora"|"SDR"|"Financeiro"|"Gestão"|"Admin / Diretoria";
type Tab="inicio"|"comissoes"|"treinamentos"|"metas"|"perfil";

export function StaffPwa(){
 const [tab,setTab]=useState<Tab>("inicio");
 const [role,setRole]=useState<Role>(()=>(localStorage.getItem("sra-staff-role") as Role)||"Vendedora");
 const cfg=useMemo(()=>roleConfig(role),[role]);
 const tabs=[['inicio','Início',Home],['comissoes','Comissões',BadgeDollarSign],['treinamentos','Treinamentos',BookOpenCheck],['metas','Metas',Target],['perfil','Perfil',UserRound]] as const;
 return <div className="st-app"><header><div><img src="/brand/sra-luck-mark.png"/><div><small>Portal da equipe</small><strong>Olá, Bianca</strong></div></div><span>{role}</span></header><main>{tab==='inicio'&&<StaffHome role={role} cfg={cfg} setTab={setTab}/>} {tab==='comissoes'&&<Commissions role={role} cfg={cfg}/>} {tab==='treinamentos'&&<Trainings role={role}/>} {tab==='metas'&&<Goals role={role} cfg={cfg}/>} {tab==='perfil'&&<Profile role={role} setRole={r=>{setRole(r);localStorage.setItem('sra-staff-role',r)}}/>}</main><nav>{tabs.map(([id,label,Icon])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}><Icon size={18}/><span>{label}</span></button>)}</nav></div>
}
function roleConfig(role:Role){if(role==='SDR')return{commission:'R$ 680,00',rule:'R$ 10 por comparecimento',goal:'68 comparecimentos',progress:82,headline:'Você está a 15 comparecimentos da sua meta do mês.'};if(role==='Financeiro')return{commission:'R$ 2.146,30',rule:'1,69% sobre atraso recuperado',goal:'R$ 90.000 recuperados',progress:76,headline:'R$ 68.400 recuperados. Continue avançando para a próxima faixa.'};if(role==='Gestão'||role==='Admin / Diretoria')return{commission:'—',rule:'Visão gerencial',goal:'Performance da operação',progress:88,headline:'Acompanhe a evolução da equipe e os indicadores da operação.'};return{commission:'R$ 1.400,00',rule:'R$ 100 por 1ª parcela paga',goal:'18 primeiras parcelas',progress:78,headline:'14 contratos já geraram comissão neste mês.'}}
function StaffHome({role,cfg,setTab}:{role:Role;cfg:ReturnType<typeof roleConfig>;setTab:(t:Tab)=>void}){return <div className="st-stack"><section className="st-hero"><div><small>{role}</small><h1>Seu desempenho em um só lugar.</h1><p>{cfg.headline}</p></div><Medal/></section><div className="st-kpis"><article><small>Comissão prevista</small><b>{cfg.commission}</b><span>{cfg.rule}</span></article><article><small>Meta atual</small><b>{cfg.progress}%</b><span>{cfg.goal}</span></article></div><section className="st-card"><div className="st-title"><div><h2>Progresso do mês</h2><p>{cfg.goal}</p></div><strong>{cfg.progress}%</strong></div><div className="st-progress"><i style={{width:`${cfg.progress}%`}}/></div><button onClick={()=>setTab('metas')}>Ver detalhes da meta <ChevronRight size={15}/></button></section><section className="st-card"><div className="st-title"><div><h2>Continue aprendendo</h2><p>Treinamentos recomendados para seu perfil.</p></div></div>{trainings.slice(0,3).map(t=><div className="st-learning" key={t.id}><PlayCircle/><div><strong>{t.title}</strong><small>{t.kind} · {t.duration}</small></div><span>{t.progress}%</span></div>)}<button onClick={()=>setTab('treinamentos')}>Ver todos os treinamentos <ChevronRight size={15}/></button></section><section className="st-card"><div className="st-title"><div><h2>Atividades recentes</h2><p>Eventos que impactaram sua remuneração.</p></div></div>{[['Contrato CTR-2026-0482','Primeira parcela paga · + R$ 100'],['Treinamento concluído','Jornada Sra. Luck'],['Meta atualizada','14 de 18 eventos validados']].map(([a,b])=><div className="st-activity" key={a}><CheckCircle2/><div><strong>{a}</strong><small>{b}</small></div></div>)}</section></div>}
function Commissions({role,cfg}:{role:Role;cfg:ReturnType<typeof roleConfig>}){const entries=role==='SDR'?[['Renata Oliveira','Compareceu','R$ 10,00'],['Juliana Costa','Compareceu','R$ 10,00'],['Mariana Silva','Compareceu','R$ 10,00']]:role==='Financeiro'?[['Carteira setembro','R$ 28.300 recuperados','R$ 478,27'],['Carteira agosto','R$ 21.800 recuperados','R$ 368,42'],['Acordos especiais','R$ 14.700 recuperados','R$ 248,43']]:[['CTR-2026-0482 · Renata','1ª parcela paga','R$ 100,00'],['CTR-2026-0310 · Carlos','1ª parcela paga','R$ 100,00'],['CTR-2026-0296 · Juliana','1ª parcela paga','R$ 100,00']];return <div className="st-stack"><div className="st-section"><h1>Comissões</h1><p>Acompanhe eventos validados e previsão do mês.</p></div><section className="st-commission-hero"><small>Previsto para setembro</small><h2>{cfg.commission}</h2><p>{cfg.rule}</p></section><section className="st-card"><h2>Como funciona</h2><p className="st-copy">{role==='Vendedora'?'Você recebe R$ 100 quando a primeira parcela do contrato vendido é confirmada como paga.':role==='SDR'?'Você recebe R$ 10 por agendamento com comparecimento confirmado, com ou sem fechamento.':role==='Financeiro'?'Inicialmente, 1,69% sobre o valor em atraso recuperado, considerando a meta base de R$ 90 mil. As faixas podem ser alteradas pela gestão.':'Acesso gerencial para acompanhar regras e consolidação das comissões.'}</p></section><section className="st-card"><h2>Eventos do período</h2>{entries.map(r=><article className="st-entry" key={r[0]}><div><strong>{r[0]}</strong><small>{r[1]}</small></div><b>{r[2]}</b></article>)}</section></div>}
function Trainings({role}:{role:Role}){return <div className="st-stack"><div className="st-section"><h1>Treinamentos</h1><p>Conteúdos da Sra. Luck para desenvolvimento contínuo.</p></div>{trainings.map(t=><section className="st-card st-course" key={t.id}><div className="st-course-art"><PlayCircle/></div><div><span>{t.audience==='Todos'||t.audience===role?'Recomendado':'Conteúdo complementar'}</span><h2>{t.title}</h2><p>{t.kind} · {t.duration}</p><div className="st-progress"><i style={{width:`${t.progress}%`}}/></div><small>{t.progress}% concluído</small></div><button>Continuar <ChevronRight size={14}/></button></section>)}</div>}
function Goals({role,cfg}:{role:Role;cfg:ReturnType<typeof roleConfig>}){return <div className="st-stack"><div className="st-section"><h1>Metas</h1><p>Indicadores e objetivos da sua função.</p></div><section className="st-goal-ring"><div style={{background:`conic-gradient(#987244 ${cfg.progress*3.6}deg,#e8ddcd 0)`}}><span><b>{cfg.progress}%</b><small>da meta</small></span></div><h2>{cfg.goal}</h2><p>{cfg.headline}</p></section><section className="st-card"><h2>Indicadores do mês</h2>{role==='Vendedora'?[['Contratos vendidos','18'],['1ª parcela paga','14'],['Aguardando 1ª parcela','4']]:role==='SDR'?[['Agendamentos','83'],['Comparecimentos','68'],['No-show','15']]:role==='Financeiro'?[['Carteira recuperada','R$ 68.400'],['Meta base','R$ 90.000'],['Comissão estimada','R$ 1.155,96']]:[['Equipe ativa','24'],['Metas no verde','18'],['Pontos de atenção','6']].map(x=>x).map(r=>r).map(r=>r)}{(role==='Vendedora'?[['Contratos vendidos','18'],['1ª parcela paga','14'],['Aguardando 1ª parcela','4']]:role==='SDR'?[['Agendamentos','83'],['Comparecimentos','68'],['No-show','15']]:role==='Financeiro'?[['Carteira recuperada','R$ 68.400'],['Meta base','R$ 90.000'],['Comissão estimada','R$ 1.155,96']]:[['Equipe ativa','24'],['Metas no verde','18'],['Pontos de atenção','6']]).map(r=><article className="st-entry" key={r[0]}><strong>{r[0]}</strong><b>{r[1]}</b></article>)}</section></div>}
function Profile({role,setRole}:{role:Role;setRole:(r:Role)=>void}){const roles:Role[]=['Vendedora','SDR','Financeiro','Gestão','Admin / Diretoria'];return <div className="st-stack"><div className="st-section"><h1>Meu perfil</h1><p>Acesso, função e preferências do portal.</p></div><section className="st-card st-profile"><div className="st-avatar">BS</div><h2>Bianca Souza</h2><span>{role}</span><small>bianca@sraluck.com.br</small></section><section className="st-card"><h2>Prévia de perfis</h2><p className="st-copy">Enquanto a autenticação por função é finalizada, use esta seleção para visualizar como o PWA se adapta a cada cargo.</p><div className="st-role-list">{roles.map(r=><button className={r===role?'active':''} key={r} onClick={()=>setRole(r)}>{r}{r===role&&<CheckCircle2 size={15}/>}</button>)}</div></section></div>}
