"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";

type FormaCusteio = "cartao" | "pix" | "cheques" | "boleto_100";
interface Financeiro { saldoRestante:number|null; formasCusteio:string[]; }
interface Solicitacao { id:string; forma_custeio:FormaCusteio; status:string; observacao:string|null; }
function moeda(v:number){return v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function label(forma:FormaCusteio){return forma==="cartao"?"Cartão de crédito":forma==="pix"?"PIX":forma==="cheques"?"Cheques":"100% boleto"}
function extra(forma:FormaCusteio){return forma==="cartao"?"taxa calculada pelo sistema":forma==="pix"?"sem taxa adicional":forma==="cheques"?"sujeito à conferência":"conforme condições do contrato"}

export function EscolherFormaPagamento(){
  const[financeiro,setFinanceiro]=useState<Financeiro>({saldoRestante:null,formasCusteio:[]});const[solicitacao,setSolicitacao]=useState<Solicitacao|null>(null);const[carregando,setCarregando]=useState(true);const[modal,setModal]=useState(false);const[forma,setForma]=useState<FormaCusteio|null>(null);const[enviando,setEnviando]=useState(false);const[erro,setErro]=useState<string|null>(null);
  async function carregar(){try{const r=await fetch("/api/cliente/agenda",{cache:"no-store"});if(!r.ok)return;const d=await r.json();setFinanceiro(d.financeiro??{saldoRestante:null,formasCusteio:[]});setSolicitacao(d.solicitacaoLiberacaoFinanceira??null)}catch{}finally{setCarregando(false)}}
  useEffect(()=>{void carregar();const t=setInterval(()=>void carregar(),5000);return()=>clearInterval(t)},[]);
  const formas=useMemo(()=>(["cartao","pix","cheques","boleto_100"] as FormaCusteio[]).filter(f=>financeiro.formasCusteio.includes(f)),[financeiro.formasCusteio]);
  const status=String(solicitacao?.status??"").toLowerCase();const recusada=status.includes("recus");const emAnalise=Boolean(solicitacao)&&!recusada;
  async function enviar(){if(!forma)return;setEnviando(true);setErro(null);try{const r=await fetch("/api/cliente/solicitacao-liberacao-financeira",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({formaCusteio:forma})});const d=await r.json();if(!r.ok)throw new Error(d.erro??"Não foi possível enviar sua solicitação.");setSolicitacao(d.solicitacao??null);setModal(false)}catch(e){setErro(e instanceof Error?e.message:"Não foi possível enviar sua solicitação.")}finally{setEnviando(false)}}
  if(carregando)return null;

  if(emAnalise)return <section className="overflow-hidden rounded-[18px] border border-[#EFE4E1] bg-white shadow-[0_10px_26px_rgba(70,42,44,.07)]"><div className="border-b border-[#F0E2C7] bg-[#FFF9F2] px-[13px] py-3"><div className="flex items-start gap-[10px]"><span className="flex h-[29px] w-[29px] flex-none items-center justify-center rounded-[8px] bg-[#F8EEDB] text-[#A77A24]"><svg width="14" height="14" viewBox="0 0 18 18" fill="none" stroke="currentColor" strokeWidth="1.25"><circle cx="9" cy="9" r="6.2"/><path d="M9 5.6V9l2.3 1.5"/></svg></span><div><div className="text-[8.5px] font-bold uppercase tracking-[.13em] text-[#A77A24]">Custeio em análise</div><div className="pt-[2px] font-heading text-[15px] font-semibold leading-[1.25] text-[#7D2434]">Recebemos sua escolha de pagamento</div><div className="pt-[3px] text-[9.6px] font-light leading-[1.45] text-[#7E6867]">{solicitacao?.observacao??"Nossa equipe está confirmando a forma de pagamento escolhida por você."}</div></div></div></div><div className="p-[14px]"><div className="rounded-[13px] border border-[#EFD9AA] bg-[#FFF9EF] px-3 py-[11px] text-[10px] font-light leading-[1.5] text-[#7A6B67]">Assim que a confirmação for concluída, a agenda da assinatura dos termos seguirá para a próxima etapa.</div></div></section>;

  return <>
    <section className="overflow-hidden rounded-[18px] border border-[#EFE4E1] bg-white shadow-[0_10px_26px_rgba(70,42,44,.07)]">
      <div className="border-b border-[#F0DDDD] bg-[#FFF7F7] px-[13px] py-3"><div className="flex items-start gap-[10px]"><span className="flex h-[29px] w-[29px] flex-none items-center justify-center rounded-[8px] bg-[#F7E9EA] text-[#B65B67]"><svg width="14" height="14" viewBox="0 0 18 18" fill="none" stroke="currentColor" strokeWidth="1.25"><path d="M9 2.8 14 4.6v3.7c0 3.1-2 5.3-5 6.6-3-1.3-5-3.5-5-6.6V4.6L9 2.8Z"/><path d="m6.7 8.8 1.5 1.5 3-3"/></svg></span><div><div className="text-[8.5px] font-bold uppercase tracking-[.13em] text-[#B65B67]">Minha agenda</div><div className="pt-[2px] font-heading text-[15px] font-semibold leading-[1.25] text-[#7D2434]">Levantamento financeiro concluído</div><div className="pt-[2px] text-[9.6px] font-light leading-[1.45] text-[#7E6867]">{recusada?"Sua forma de custeio anterior precisou de ajuste. Escolha novamente como será realizado o pagamento.":"Informe como será realizado o custeio do saldo restante para seguir na jornada."}</div></div></div></div>
      <div className="p-[14px]"><div className="rounded-[14px] border border-[#EAD7AE] bg-[#FFF9EF] p-[13px] text-center"><div className="text-[8.5px] font-semibold uppercase tracking-[.12em] text-[#A77A24]">Saldo restante do contrato</div><div className="pt-[3px] font-heading text-[25px] font-semibold text-[#7D2434]">{moeda(Number(financeiro.saldoRestante??0))}</div><div className="pt-[2px] text-[9.7px] font-light text-[#8A7B77]">Valor apurado pelo financeiro para esta etapa.</div></div><button type="button" onClick={()=>{setErro(null);setForma(solicitacao?.forma_custeio??null);setModal(true)}} className="mt-[11px] w-full rounded-[11px] bg-[#6B1F2E] px-3 py-[11px] text-[10.8px] font-semibold text-white">Escolher forma de custeio</button></div>
    </section>

    <AnimatePresence>{modal&&<><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>!enviando&&setModal(false)} className="fixed inset-0 z-[80] bg-[rgba(38,23,25,.30)] backdrop-blur-[2px]"/><motion.div initial={{y:"100%"}} animate={{y:0}} exit={{y:"100%"}} transition={{duration:.2}} className="fixed bottom-0 left-1/2 z-[81] w-full max-w-[430px] -translate-x-1/2 px-[10px] pb-[max(12px,env(safe-area-inset-bottom))]"><div className="rounded-[24px_24px_18px_18px] border border-[#EADFDB] bg-white px-[14px] pb-[15px] pt-[9px] shadow-[0_-16px_45px_rgba(48,26,30,.18)]"><div className="mx-auto mb-3 h-1 w-[38px] rounded-full bg-[#E7DCD8]"/><div className="flex items-start justify-between gap-3"><div><div className="text-[8.5px] font-bold uppercase tracking-[.14em] text-[#B65B67]">Custeio do saldo restante</div><div className="pt-[3px] font-heading text-[21px] font-semibold text-[#7D2434]">Como será realizado o pagamento?</div><div className="pt-1 text-[10px] font-light leading-[1.5] text-[#7A6B67]">Escolha uma das formas autorizadas pelo financeiro. As opções são carregadas conforme a configuração do seu contrato.</div></div><button type="button" onClick={()=>!enviando&&setModal(false)} className="flex h-7 w-7 flex-none items-center justify-center rounded-full bg-[#F7EFED] text-[#7D2434]">×</button></div><div className="mt-3 flex flex-col gap-[7px]">{formas.map(f=><button key={f} type="button" onClick={()=>setForma(f)} className="flex items-center justify-between rounded-[12px] border px-3 py-[11px] text-left" style={forma===f?{borderColor:"#7D2434",background:"#F7EFED",color:"#6B1F2E"}:{borderColor:"#EADFDB",background:"#FFF",color:"#5E4A46"}}><span className="text-[11px] font-medium">{label(f)}</span><span className="text-[10px] text-[#B65B67]">{extra(f)}</span></button>)}{formas.length===0&&<div className="rounded-[12px] border border-[#F0D3D1] bg-[#FBEBEA] p-3 text-[10px] text-[#8F2A25]">Nenhuma forma de custeio está disponível no momento.</div>}</div>{erro&&<div className="mt-2 rounded-[11px] border border-[#F0D3D1] bg-[#FBEBEA] p-[9px] text-[9.8px] text-[#8F2A25]">{erro}</div>}<button type="button" disabled={!forma||enviando||formas.length===0} onClick={()=>void enviar()} className="mt-[11px] w-full rounded-[12px] bg-[#6B1F2E] p-3 text-[11.5px] font-medium text-white disabled:opacity-40">{enviando?"Confirmando...":"Confirmar forma de custeio"}</button></div></motion.div></>}</AnimatePresence>
  </>;
}
