import { createServiceSupabaseClient, type Env } from "./supabase";
import { getCookie, verificarTokenAdmin } from "./session";

type Json = Record<string, any>;
function json(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" } }); }
async function body(request: Request): Promise<Json> { try { return await request.json(); } catch { return {}; } }
async function exigirAdmin(request: Request, env: Env) { if (!env.CLIENTE_SESSION_SECRET) return json({ erro: "Serviço temporariamente indisponível." }, 503); const token=getCookie(request,"admin_session"); return (await verificarTokenAdmin(token,env.CLIENTE_SESSION_SECRET))?null:json({erro:"Sessão administrativa expirada."},401); }

export async function adminApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url), path=url.pathname;
  if(!path.startsWith("/api/admin/")||["/api/admin/auth","/api/admin/session","/api/admin/logout","/api/admin/visao-geral"].includes(path))return null;
  const auth=await exigirAdmin(request,env);if(auth)return auth;const supabase=createServiceSupabaseClient(env);
  if(path==="/api/admin/clientes"&&request.method==="GET"){const {data,error}=await supabase.from("clientes").select("id,nome_completo,cpf,data_nascimento,telefone,email,procedimento,medico,hospital,consultora,valor_contrato,taxa_administrativa_percentual,status_cirurgia,status_financeiro,observacoes_internas,quantidade_parcelas,status_revisao_financeira,data_atingiu_percentual,observacao_revisao_financeira,financeiro_saldo_restante,financeiro_taxa_cartao,financeiro_total_com_taxa,financeiro_formas_custeio,financeiro_confirmado_em,custeio_confirmado_em,ativo,created_at,updated_at").order("created_at",{ascending:false});if(error)return json({erro:error.message},500);const {data:boletos}=await supabase.from("boletos").select("cliente_id,status");const {data:agendamentos}=await supabase.from("agendamentos").select("cliente_id,status,horario_termos,termos_assinados_em,datas(data)").in("status",["confirmado","realizado"]);const resumo=new Map<string,{total:number;pagos:number}>();for(const b of boletos??[]){const r=resumo.get(b.cliente_id)??{total:0,pagos:0};r.total++;if(b.status==="pago")r.pagos++;resumo.set(b.cliente_id,r);}const agenda=new Map<string,any>();for(const a of (agendamentos??[]) as any[]){const d=Array.isArray(a.datas)?a.datas[0]?.data:a.datas?.data;const old=agenda.get(a.cliente_id);if(!old||(a.status==="realizado"&&old.status==="confirmado"))agenda.set(a.cliente_id,{data:d??null,horario:a.horario_termos?String(a.horario_termos).slice(0,5):null,termosAssinadosEm:a.termos_assinados_em??null,status:a.status});}return json({clientes:(data??[]).map((c:any)=>{const r=resumo.get(c.id),a=agenda.get(c.id);return {...c,porcentagem_pagamento:r?.total?Math.round(r.pagos/r.total*1000)/10:null,parcelas_pagas:r?.pagos??null,parcelas_total:r?.total??null,termos_assinados_em:a?.termosAssinadosEm??null,proximo_agendamento_data:a?.status==="confirmado"?a.data:null,proximo_agendamento_horario:a?.status==="confirmado"?a.horario:null};})});}
  if(path==="/api/admin/clientes"&&request.method==="POST"){const b=await body(request),cpf=String(b.cpf??"").replace(/\D/g,"");if(!b.nomeCompleto||cpf.length!==11||!b.dataNascimento)return json({erro:"Nome, CPF e data de nascimento são obrigatórios."},400);const {data,error}=await supabase.from("clientes").insert({nome_completo:b.nomeCompleto,cpf,data_nascimento:b.dataNascimento,telefone:b.telefone||null,email:b.email||null,procedimento:b.procedimento||null,medico:b.medico||null,hospital:b.hospital||null,consultora:b.consultora||null,valor_contrato:Number(b.valorContrato)||0,taxa_administrativa_percentual:Number(b.taxaAdministrativaPercentual)||0,observacoes_internas:b.observacoes||null,ativo:b.ativo!==false,status_cirurgia:"nao_agendada",status_financeiro:"a_pagar"}).select("*").single();if(error)return json({erro:error.code==="23505"?"Já existe uma cliente cadastrada com esse CPF.":error.message},400);return json({cliente:data});}
  const cliente=path.match(/^\/api\/admin\/clientes\/([^/]+)$/);if(cliente&&request.method==="PATCH"){const b=await body(request),id=decodeURIComponent(cliente[1]),patch:any={};const map:any={nomeCompleto:"nome_completo",cpf:"cpf",dataNascimento:"data_nascimento",telefone:"telefone",email:"email",procedimento:"procedimento",medico:"medico",hospital:"hospital",consultora:"consultora",valorContrato:"valor_contrato",taxaAdministrativaPercentual:"taxa_administrativa_percentual",observacoes:"observacoes_internas",ativo:"ativo"};for(const [a,k]of Object.entries(map))if(b[a]!==undefined)patch[k]=a==="cpf"?String(b[a]).replace(/\D/g,""):b[a];const {data,error}=await supabase.from("clientes").update(patch).eq("id",id).select("*").single();if(error)return json({erro:error.message},400);return json({cliente:data});}
  const cb=path.match(/^\/api\/admin\/clientes\/([^/]+)\/(boletos|parcelas)$/);if(cb){const id=decodeURIComponent(cb[1]);if(request.method==="GET"){const {data,error}=await supabase.from("boletos").select("id,cliente_id,numero_parcela,total_parcelas,valor,data_vencimento,status,comprovante_url,boleto_url,data_pagamento,observacoes,suspensa,suspensa_em,suspensa_por,created_at,updated_at").eq("cliente_id",id).order("numero_parcela",{ascending:true});if(error)return json({erro:error.message},500);return json({boletos:data??[],parcelas:data??[]});}const b=await body(request);if(request.method==="POST"&&cb[2]==="boletos"){const {data:c}=await supabase.from("clientes").select("valor_contrato,quantidade_parcelas,taxa_administrativa_percentual").eq("id",id).maybeSingle();const total=Math.max(Number(b.totalParcelas??c?.quantidade_parcelas??1),1);const valor=Number(b.valor??((Number(c?.valor_contrato??0)*(1+Number(c?.taxa_administrativa_percentual??0)/100))/total));const rows=Array.from({length:total},(_,i)=>({cliente_id:id,numero_parcela:i+1,total_parcelas:total,valor,data_vencimento:b.dataVencimento??null,status:"pendente"}));const {data,error}=await supabase.from("boletos").insert(rows).select("*");if(error)return json({erro:error.message},400);return json({boletos:data});}if(request.method==="POST"&&cb[2]==="parcelas"){if(b.acao==="excluir"&&b.boletoId){const {error}=await supabase.from("boletos").delete().eq("id",b.boletoId).eq("cliente_id",id);if(error)return json({erro:error.message},400);return json({ok:true});}if(b.acao==="editar"&&b.boletoId){const patch:any={};if(b.valor!==undefined)patch.valor=Number(b.valor);if(b.dataVencimento!==undefined)patch.data_vencimento=b.dataVencimento||null;const {data,error}=await supabase.from("boletos").update(patch).eq("id",b.boletoId).eq("cliente_id",id).select("*").single();if(error)return json({erro:error.message},400);return json({boleto:data});}}if(request.method==="PATCH"){const idB=b.boletoId;if(!idB)return json({erro:"Boleto não informado."},400);const patch:any={};if(b.valor!==undefined)patch.valor=Number(b.valor);if(b.dataVencimento!==undefined)patch.data_vencimento=b.dataVencimento||null;if(b.status!==undefined)patch.status=b.status;const {data,error}=await supabase.from("boletos").update(patch).eq("id",idB).eq("cliente_id",id).select("*").single();if(error)return json({erro:error.message},400);return json({boleto:data});}}
  if(path==="/api/admin/boletos"&&request.method==="GET"){let q=supabase.from("boletos").select("id,cliente_id,numero_parcela,total_parcelas,valor,data_vencimento,status,comprovante_url,boleto_url,data_pagamento,observacoes,suspensa,suspensa_em,suspensa_por,created_at,updated_at,clientes(id,nome_completo,cpf)").order("created_at",{ascending:false});const status=url.searchParams.get("status"),cid=url.searchParams.get("cliente_id");if(status&&status!=="todos")q=q.eq("status",status);if(cid)q=q.eq("cliente_id",cid);const {data,error}=await q;if(error)return json({erro:error.message},500);return json({boletos:(data??[]).map((x:any)=>({...x,valor:Number(x.valor)}))});}
  const boleto=path.match(/^\/api\/admin\/boletos\/([^/]+)$/);if(boleto&&request.method==="PATCH"){const id=decodeURIComponent(boleto[1]),b=await body(request),acao=b.acao;const status=acao==="confirmar"?"pago":acao==="rejeitar"?"rejeitado":b.status;if(!status)return json({erro:"Ação de pagamento inválida."},400);const {data,error}=await supabase.from("boletos").update({status,observacoes:b.observacoes??undefined,data_pagamento:acao==="confirmar"?new Date().toISOString().slice(0,10):undefined}).eq("id",id).select("*").single();if(error)return json({erro:error.message},400);return json({boleto:data});}
  if(path==="/api/admin/boletos/lote"&&request.method==="PATCH"){const b=await body(request),ids=Array.isArray(b.ids)?b.ids:[];if(!ids.length)return json({erro:"Nenhum boleto selecionado."},400);const {data,error}=await supabase.from("boletos").update({status:b.status??"pago",data_pagamento:b.dataPagamento??new Date().toISOString().slice(0,10)}).in("id",ids).select("*");if(error)return json({erro:error.message},400);return json({boletos:data??[]});}
  if(path==="/api/admin/datas"&&request.method==="GET"){const ano=Number(url.searchParams.get("ano")),mes=Number(url.searchParams.get("mes"));let q=supabase.from("datas").select("*").order("data",{ascending:true});if(ano&&mes){const ini=`${ano}-${String(mes).padStart(2,"0")}-01`,next=mes===12?`${ano+1}-01-01`:`${ano}-${String(mes+1).padStart(2,"0")}-01`;q=q.gte("data",ini).lt("data",next);}const {data,error}=await q;if(error)return json({erro:error.message},500);const ids=(data??[]).map((x:any)=>x.id);let ag:any[]=[];if(ids.length){const r=await supabase.from("agendamentos").select("data_id,cliente_id,status").in("data_id",ids).eq("status","confirmado");ag=r.data??[];}const counts=new Map<string,number>();for(const a of ag)counts.set(a.data_id,(counts.get(a.data_id)??0)+1);return json({datas:(data??[]).map((x:any)=>({...x,vagasOcupadas:counts.get(x.id)??0}))});}
  if(path==="/api/admin/datas"&&request.method==="POST"){const b=await body(request);if(!b.data)return json({erro:"Data obrigatória."},400);const {data,error}=await supabase.from("datas").insert({data:b.data,vagas_totais:Number(b.vagasTotais??1),status:"disponivel"}).select("*").single();if(error)return json({erro:error.code==="23505"?"Esta data já está liberada.":error.message},400);return json({data});}
  const dm=path.match(/^\/api\/admin\/datas\/([^/]+)$/);if(dm&&(request.method==="PATCH"||request.method==="DELETE")){const id=decodeURIComponent(dm[1]);if(request.method==="DELETE"){const {error}=await supabase.from("datas").delete().eq("id",id);if(error)return json({erro:error.message},400);return json({ok:true});}const b=await body(request),patch:any={};if(b.status!==undefined)patch.status=b.status;if(b.vagasTotais!==undefined)patch.vagas_totais=Math.max(Number(b.vagasTotais),0);const {data,error}=await supabase.from("datas").update(patch).eq("id",id).select("*").single();if(error)return json({erro:error.message},400);return json({data});}
  if(path==="/api/admin/configuracoes"){if(request.method==="GET"){const {data,error}=await supabase.from("configuracoes").select("*").maybeSingle();if(error)return json({erro:error.message},500);return json({configuracoes:data??{}});}if(request.method==="PATCH"){const b=await body(request),patch:any={};if(b.nomeClinica!==undefined)patch.nome_clinica=b.nomeClinica;if(b.metaOrcamentoMensal!==undefined)patch.meta_orcamento_mensal=Number(b.metaOrcamentoMensal);if(b.fraseSonho!==undefined)patch.frase_sonho=b.fraseSonho;if(b.agendaLiberacaoFinanceiraBloqueada!==undefined)patch.agenda_liberacao_financeira_bloqueada=Boolean(b.agendaLiberacaoFinanceiraBloqueada);const r=await supabase.from("configuracoes").update(patch).eq("id",1).select("*").maybeSingle();if(r.error)return json({erro:r.error.message},400);return json({configuracoes:r.data});}}
  if(path==="/api/admin/clientes-agendamentos"&&request.method==="GET"){const {data,error}=await supabase.from("agendamentos").select("id,cliente_id,status,horario_termos,termos_assinados_em,datas(id,data,status),clientes(id,nome_completo,cpf)").order("created_at",{ascending:false});if(error)return json({erro:error.message},500);return json({agendamentos:data??[]});}
  if(path==="/api/admin/agenda-mensal"&&request.method==="GET"){const ano=Number(url.searchParams.get("ano"))||new Date().getFullYear();const {data,error}=await supabase.from("agendamentos").select("id,cliente_id,status,horario_termos,datas(data),clientes(nome_completo)").gte("datas.data",`${ano}-01-01`).lt("datas.data",`${ano+1}-01-01`).order("created_at",{ascending:true});if(error)return json({erro:error.message},500);return json({agendamentos:data??[]});}
  if(path==="/api/admin/remarcacoes"){if(request.method==="GET"){const {data,error}=await supabase.from("remarcacoes").select("*").order("created_at",{ascending:false}).limit(100);if(error)return json({remarcacoes:[]});return json({remarcacoes:data??[]});}if(request.method==="POST"){const b=await body(request);if(!b.id||!["aprovar","recusar"].includes(b.acao))return json({erro:"Solicitação inválida."},400);const {data,error}=await supabase.from("remarcacoes").update({status:b.acao==="aprovar"?"aprovada":"recusada"}).eq("id",b.id).select("*").single();if(error)return json({erro:error.message},400);return json({remarcacao:data});}}
  if(path==="/api/admin/datas-liberacao-financeira"&&request.method==="GET"){const {data,error}=await supabase.from("datas_liberacao_financeira").select("*").order("data",{ascending:true});if(error)return json({erro:error.message},500);return json({datas:data??[]});}
  if(path==="/api/admin/previsoes-liberacao"&&request.method==="GET"){const {data,error}=await supabase.from("agendamentos").select("id,cliente_id,previsao_liberacao_financeira,status,clientes(id,nome_completo,cpf)").not("previsao_liberacao_financeira","is",null).order("previsao_liberacao_financeira",{ascending:true});if(error)return json({previsoes:[]});return json({previsoes:data??[]});}
  if((path==="/api/admin/liberacoes-financeiras"||path==="/api/admin/solicitacoes-liberacao-financeira")&&request.method==="GET"){const table=path.includes("solicitacoes")?"solicitacoes_liberacao_financeira":"liberacoes_financeiras";const {data,error}=await supabase.from(table).select("*").order("created_at",{ascending:false});if(error)return json({erro:error.message},500);return json({[path.includes("solicitacoes")?"solicitacoes":"liberacoes"]:data??[]});}
  const rev=path.match(/^\/api\/admin\/clientes\/([^/]+)\/revisao-financeira$/);if(rev&&request.method==="POST"){const id=decodeURIComponent(rev[1]),b=await body(request),patch:any={status_revisao_financeira:b.decisao,observacao_revisao_financeira:b.observacao??null};if(b.saldoRestante!==undefined)patch.financeiro_saldo_restante=Number(b.saldoRestante);if(b.taxaCartao!==undefined)patch.financeiro_taxa_cartao=Number(b.taxaCartao);if(b.formasCusteio!==undefined)patch.financeiro_formas_custeio=b.formasCusteio;if(b.decisao==="aprovada")patch.financeiro_confirmado_em=new Date().toISOString();const {data,error}=await supabase.from("clientes").update(patch).eq("id",id).select("*").single();if(error)return json({erro:error.message},400);return json({cliente:data});}
  return json({erro:"Rota administrativa ainda não migrada.",rota:path},404);
}
